webex/react-widgets

src/index.js
Added the `demo.js` file to the root bundle `index.js` the demo is added to the bundle.
=> fix(demo): Add demo to root bundle

packages/node_modules/@ciscospark/widget-message-meet/README.md
Error in the docs for the browser globals methods.
=> docs(widget-message-meet): Fix wrong name in docs

package.json, packages/node_modules/@ciscospark/widget-message-meet/src/store.js
Fix the issue we had a workaround for:
https://github.com/evgenyrodionov/redux-logger/issues/210
=> fix: removing workaround for redux-logger

packages/node_modules/@ciscospark/react-component-video/src/index.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.js, packages/node_modules/@ciscospark/widget-meet/src/components/call-active/index.js, packages/node_modules/@ciscospark/widget-meet/src/container.js
With `createObjectURL` losing support for media streams, we've created a work around for the react video element to support a `srcObject`
=> feat(widget-meet): Render video srcObject instead of url

packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.js
When an outgoing call was declined by the remote party, the disconnect event would not relinquish the mic and camera. This solves that issue. Will be working on a fix in the sdk as well.
=> feat(redux-module-media): hangup call on disconnect

packages/node_modules/@ciscospark/react-redux-spark/src/component.js
If you give a bad token, it will constantly try to register device.
=> fix(react-redux-spark): stop attempting to register on failure

packages/node_modules/@ciscospark/widget-base/README.md, packages/node_modules/@ciscospark/widget-base/src/data-api.js
First pass at adding events for data api. This basically allows the data api to use browser globals to init the widgets and essentially give you access to the `window.ciscospark.widget(el)` method. By doing this we also hook in the ampersand events, and provide access to the widgets through global stores.
Another option would be to init the data api based widgets different, but I figured that would be a pain to maintain and cause confusion.
=> feat(widget-base): Allow data api to use browser globals if available

packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/widget-message/src/container.js
Noticed the `isListening` flag was being used for both activity and typing. Setting this to be more explicit
=> fix(widget-message): add detail is listening flags

packages/node_modules/@ciscospark/react-container-read-receipts/src/index.js, packages/node_modules/@ciscospark/redux-module-avatar/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/redux-module-avatar/src/index.js, packages/node_modules/@ciscospark/redux-module-avatar/src/index.test.js, packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/reducer.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
This turned out a bit bigger than expected, so you may want to go commit by commit.
Basically, all individual avatar handling is now in the avatar module. You can call "fetch avatar" over and over for a user and it will only process if we haven't seen that user before. 
There's also some cleanup in spaces widget to only get the avatars we need for display instead of **EVERYONE**
=> Avatar fetching

package.json
Since we are locked to the sdk's eslint version, let's not get greenkeeper updates on it in this repo.
=> chore: add greenkeeper ignore for eslint

Jenkinsfile, packages/node_modules/@ciscospark/widget-recents-demo/src/components/demo-widget-recents/index.js, packages/node_modules/@ciscospark/widget-recents-demo/src/components/demo-widget-recents/styles.css, packages/node_modules/@ciscospark/widget-recents-demo/src/index.html, packages/node_modules/@ciscospark/widget-recents-demo/src/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/styles.css, packages/node_modules/@ciscospark/widget-space-demo/src/index.html, packages/node_modules/@ciscospark/widget-space-demo/src/index.js, scripts/webpack/webpack.dev.babel.js, scripts/webpack/webpack.prod.babel.js
Instead of building one giant bundle for demos, we will have the demo code be a bundle, then utilize the global method of actually creating and opening widgets.
=> Convert demos to use widget bundles and global methods

Jenkinsfile
This should resolve the issue we had where a change to Jenkinsfile doesn't get pulled in during build.
=> chore: add jenkinsfile upstream change check

packages/node_modules/@ciscospark/redux-module-teams/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/redux-module-teams/src/index.js
Fixes issue that causes looping retrieval of teams.
=> fix(redux-module-teams): Fix wrong action names

test/journeys/lib/test-helpers/space-widget/messaging.js
After watching all of the tests from today, sometimes the next file transfer will go across before the receipt message gets posted. Also, there was a weird assertion in send message that shouldn't be there.
=> test(journeys): add message receipt to file xfer tests

packages/node_modules/@ciscospark/redux-module-media/src/actions.js
Still needs investigation on the js-sdk side, but activeParticipantsCount needs to be manually calculated for now.
https://voxeolabs.atlassian.net/browse/SSDK-1421
=> fix(redux-module-media): compute activeParticipantsCount for call state

packages/node_modules/@ciscospark/widget-recents-demo/src/components/token-input/index.js, packages/node_modules/@ciscospark/widget-recents-demo/src/components/token-input/styles.css, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/styles.css, packages/node_modules/@ciscospark/widget-space-demo/src/components/token-input/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/token-input/styles.css, test/journeys/specs/tap/upcoming.js.skip
A slow migration away from material UI. `<TextField>` does way too much and is difficult to work with via automation.
=> Change demo inputs from TextField to input

packages/node_modules/@ciscospark/widget-base/src/constructor.js, packages/node_modules/@ciscospark/widget-meet/src/container.js
There was a missing `return` in this function to propagate up to the `.remove` global function.
=> remove widget features and fixes

packages/node_modules/@ciscospark/widget-roster/src/index.js
=> fix(widget-roster): fix name of the roster from incorrect 'message'

packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js, packages/node_modules/@ciscospark/widget-recents/src/container.js
When a delete/tombstone activity arrives, we need to get the last visible activity for that space to display in the preview area. We don't have conversation history downloaded so we need to refresh that space. Since `conversations/{id}` endpoint doesn't support latestActivity filter, we have to do it ourselves.
=> Recents - refresh space when a delete activity arrives

packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-space/src/container.js, wdio.conf.js
Added a few things that the web client has. 
* If the window isn't active when the new activity arrives, we won't mark it as read. (previously, if it was scrolled to the bottom, it would auto-ack no matter what the status of the widget/window was)
* Moving the mouse while scrolled to the bottom will mark as read
=> Mark space read improvements

packages/node_modules/@ciscospark/widget-message/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/container.js
Should follow this:
* Lock scroll to bottom on initial load
* Scroll locks to the bottom unless user scrolls up
* once the user scrolls to bottom, it locks again
* activity is marked read when window has focus and is scrolled to the bottom
* if list manually scrolls to the bottom, mark as read even if not in focus (can scroll out of focus on mac)
=> Scroll lock behavior

packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.test.js, packages/node_modules/@ciscospark/widget-meet/src/selector.js, packages/node_modules/@ciscospark/widget-recents/src/actions.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/reducer.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
This is the first part of the recents call tracking feature, but broken into a more manageable PR. It does two things:
- Converts call objects in media module to records
- Uses media module for incoming call tracking in Recents widget
=> Media Module: Call objects as Records

package.json
=> chore(package): update babel-plugin-lodash to version 3.3.2

packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.test.js, packages/node_modules/@ciscospark/widget-meet/src/selector.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, packages/node_modules/@ciscospark/widget-space/src/selector.js
Our recents widget will not hide the incoming call screen if the call is handled outside of the recents widget. This will handle the "decline from elsewhere" state. The "answer from elsewhere" state will need an sdk feature.
=> fix(redux-module-media): listen for declined incoming events

CHANGELOG.md, Jenkinsfile, README.md, package.json
We'll want to run this with #no-push once Jenkins is working again to make sure everything bumps properly, but it ran fine locally.
Our release commits didn't follow conventional commits, so they don't have proper CHANGELOG entries. (But they will after this)
=> chore: add standard-version

Jenkinsfile
Tags were being cleared and never refetched.
Causing the release process not to be able to find previous version.
This way matches the order the js-sdk works.
=> chore(Jenkinsfile): git checkout reordering

scripts/utils/publish.js
Changed the script to module exports to match the rest of the scripts. When it was being required, it wasn't looking at the `default` object.
=> chore(tooling): fix publish script

Jenkinsfile
- Fix NPM publishing
- Backup and restore existing .npmrc file in the shared slave $HOME directory
=> Fix NPM publishing

Jenkinsfile
- Add `warn` method that was not present (caused Jenkins failure). 
- I expect there will be more work after this because we're still getting into a warning state, but hopefully the printed error message will offer another clue.
=> Fix NPM publish: add warn method

Jenkinsfile
Removing the backup since Andrew says they do not need it. There is an exit 1 being thrown somewhere. Trying to narrow that down as well.
=> Fix NPM publish: remove .npmrc backup

packages/node_modules/@ciscospark/react-component-icon/src/styles.css
Still not 100% on font loading with webpack via create-react-app, but this is definitely needed to start.
=> style(icon): use camel case for main

packages/node_modules/@ciscospark/react-component-space-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-space-item/src/index.js, packages/node_modules/@ciscospark/react-component-space-item/src/index.test.js, packages/node_modules/@ciscospark/react-component-space-item/src/styles.css, packages/node_modules/@ciscospark/react-component-spaces-list/src/index.js, samples/recents-components/index.js
This adds an activeSpaceId prop to the `react-component-spaces-list` and `react-component-space-item`. The idea being you pass it into the list itself and each space item checks if it's "active" or not. When it is, it adds an `.active` class to the component. 
Question:
I've never really used snapshots before. I wanted to explicitly assert that the `active` class was added to the component (since the first time my snapshot rendered, it wasn't). Is there a better way to do that?
Todo: Add tests for the spaces-list component? There's none presently.
=> feat(space-item): add active prop

packages/node_modules/@ciscospark/react-container-read-receipts/src/selectors.js, scripts/webpack/webpack.dev.babel.js
If the read receipt component rendered before activities loaded a js error would throw on undefined.
=>  fix(r-c-read-receipts): add support for empty activities

packages/node_modules/@ciscospark/react-component-activity-item/src/index.js, packages/node_modules/@ciscospark/react-component-activity-list/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-file/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-files/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-thumbnail/src/index.js, packages/node_modules/@ciscospark/react-component-activity-system-message/src/index.js, packages/node_modules/@ciscospark/react-component-day-separator/src/index.js, packages/node_modules/@ciscospark/react-component-file-share-display/src/index.js, packages/node_modules/@ciscospark/react-component-file-staging-area/src/index.js
converts PropTypes.object to PropTypes.shape under react-component-* folders only.
=> refactor(react-component): converts PropTypes.object to PropTypes.shape

packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/errors.js, wdio.conf.js
The demo for disabling activities was added to widget-demo, which is not available on the CDN. This PR will make those options appear on the CDN space widget demo.
=> feat(widget-space-demo): add option to disable default activities

package.json, scripts/publish/commands/components.js, scripts/start/commands/samples.js, scripts/utils/build.js, scripts/utils/exec.js, scripts/utils/git.js, scripts/utils/package.js, scripts/utils/publish.js, scripts/webpack/webpack.base.babel.js, scripts/webpack/webpack.dev.babel.js, scripts/webpack/webpack.prod.babel.js
Utilizes the [environment variable config](https://webpack.js.org/guides/environment-variables/) to provide a starting string for the css class name.
That way, if you run `npm build:package widget-space` it will name all css classes with `widget-space--[classname]--[hash]`.
=> chore(tooling): use webpack env command line feature

scripts/utils/git.js
When we switched to the `execa` method of running commands, the previous `String()` method of interpreting the results no longer works.
Also removed the unused `diff` command, since we hardcode diff into the Jenkinsfile. If needed in the future, we can get the current version from the sdk package.
=> fix(tooling): use proper shell result for git commands

packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/actions.test.js
Do not store inactive calls that come in as a created call. 
When placing a call and hanging up before the other party answers, we get a locus event about our disconnection in the form of a participant update. Unfortunately, since the call went to “inactive” due to the user hanging up, the sdk already removed the call from the “emittedCalls” collection.  The sdk emits a “call:created” event because it sees it as a new call (one that isn’t in the emittedCalls collection).
=> feat(redux-module-media): ignore inactive created calls

packages/node_modules/@ciscospark/react-redux-spark-fixtures/src/__fixtures__/spark.js, packages/node_modules/@ciscospark/react-redux-spark/src/component.js, packages/node_modules/@ciscospark/react-redux-spark/src/spark.js, packages/node_modules/@ciscospark/spark-widget-base/src/enhancers/withInitialState.js, packages/node_modules/@ciscospark/spark-widget-base/src/index.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/index.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/setup.js
Every once in a while client metrics causes bugs in our code that breaks the widgets. The current implementation is not great and probably producing some bad metrics. We'll remove it for now until we have time to implement it correctly. Maybe with segment
=> chore: remove metrics from widgets for now

packages/node_modules/@ciscospark/widget-meet/src/components/call-active/styles.css, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/events.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, test/journeys/lib/events.js, test/journeys/specs/recents/global/basic.js, test/journeys/testplan.md
At some point during the recents list changes a few weeks back the spaces list reference got switched to raw spaces and the events were missing the fields needed to create full events. I added those back in and put in some event tests in the journey tests to at least check fields are not empty.
=> fix(widget-recents): re-add missing event fields

packages/node_modules/@ciscospark/react-component-activity-system-message/src/index.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.test.js, packages/node_modules/@ciscospark/widget-message/src/__snapshots__/selector.test.js.snap, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/selector.js
Content update activities come back from the conversation api out of (published time) order, so we need to remove them from the store and not count them in our max date calculation.
(Most of this code was taken from the web client's handling of activities)
=> filter update content activities from store

packages/node_modules/@webex/private-react-component-token-input/src/index.js
Tap tests may fail due to the aria labels being the same for input and radio buttons
=> fix(token-input): update aria labels to match previous use

test/journeys/specs/tap/widget-recents/index.js, test/journeys/specs/tap/widget-space/oneOnOne.js, test/journeys/specs/tap/widget-space/space.js
When moving to another test suite, previous user was still logged in. Added a flush of the cookies in an "after" block for each tap test.
=> fix(tap): clear cookies after tests

package-lock.json, package.json
Closes #818 and #530 
Manual testing looks good with the latest version.
=> Greenkeeper/postcss modules 1.3.2

packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.test.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js
The `if` logic was a bit off and filtering too many conversation activities causing file attachments coming from the conversation server to not be shown.
There is also a commit for a quick demo fix. I can separate into a different PR if needed.
=> fix(r-m-conversation): apply proper update content filter

test/journeys/specs/space/dataApi/startup-settings.js
This test fails due to it showing a call already in progress.
Until we can determine the cause (bug ticket SPARK-36716), skip the failing test.
=> test(journeys): skip start call setting test

.circleci/config.yml
This *should* fix the error with reporting a success on a sauce crash type error
=> fix(circleci): error on multiline command doesn't fail build

Jenkinsfile
I cannot find any documentation anymore that says publish tokens must be in the user's npmrc file. Going to attempt this, but if it fails, I'll do another PR for cleaning up the home directory npmrc.
=> Use project based npmrc for publish

packages/node_modules/@ciscospark/redux-module-media/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/actions.test.js, packages/node_modules/@ciscospark/widget-meet/src/enhancers/withCallHandlers.js, scripts/webpack/webpack.transpile.babel.js, tsconfig.json
We had the smarts to not display video on an audio only call, but we didn't tell that to the sdk when answering the call. It was throwing an error trying to display the video in an element that didn't exist.
=> Add constraints to incoming call answer

Jenkinsfile
The public path variable is what gets injected into the webpack build of the `index.html` file. I had set it to the incorrect path.
=> chore(Jenkinsfile): update public path for demo

Jenkinsfile
Circle CI tests have been migrated over. This will make it completely on int-b.
=> chore(Jenkinsfile): update tests with int environment

Jenkinsfile, scripts/build/commands/journey.js, test/journeys/lib/test-helpers/demo.js, test/journeys/lib/test-helpers/index.js, test/journeys/lib/test-helpers/space-widget/messaging.js, test/journeys/specs/smoke/demo.js, test/journeys/testplan.md, wdio.conf.js
Since widget-demo uses all the widgets via react, might as well just test it.
We should be able to migrate our tap tests to use this test suite as well.
=> Journey tests for react implementation

packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/styles.css
This will make the loaded widgets "sticky" to the bottom of the screen vs having a dedicated space at the bottom of the page.
=> feat(widget-demo): add sticky mode support

packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/external-control.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-space/README.md, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/activity-menu.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/external-control.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/index.js, packages/node_modules/@ciscospark/widget-space/src/events.js, packages/node_modules/@ciscospark/widget-space/src/index.js, test/journeys/lib/test-helpers/demo.js, test/journeys/specs/smoke/demo.js, test/journeys/testplan.md
Adds a react prop `setCurrentActivity` that allows react users of the widgets to control the current activity.
=> feat(widget-space): ability to control selected activity externally

packages/node_modules/@ciscospark/redux-module-users/src/__snapshots__/helpers.test.js.snap, packages/node_modules/@ciscospark/redux-module-users/src/helpers.js, packages/node_modules/@ciscospark/redux-module-users/src/helpers.test.js
In some instances, a participant object comes back with no displayName.
=> fix(r-m-users): add support for empty displayName

test/journeys/specs/smoke/widget-recents/index.js, test/journeys/testplan.md
I could not get this test to fail when moving it out of the group message describe block. I think that might have been the cause, we'll see.
=> test(journeys): move one on one event test out of group tests

.circleci/config.yml
Adds firefox testing back to circle but added as a new workflow job that runs at the same time (if circle has availability)
=> chore(circle): reenable firefox testing

packages/node_modules/@ciscospark/widget-roster/src/components/external-participant/styles.css
The `People outside your company are included in this space` text was misaligned with the icon. This fixes the issue.
In regular mode:
In full width mode:
=> style(widget-roster): align external message

package.json, packages/node_modules/@ciscospark/react-component-typing-avatar/src/styles.css
The Avatars are aligned now.
How to test:
Open a space widget on a room that contains both types of avatars (initials and images) in the `read-receipts` div and make sure that they are aligned.
=> Avatars are not aligned

packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.test.js
We were trying to get the "toPersonId" space detail to fetch an avatar. Unfortunately, this is a calculated property, which isn't available on the direct object, so we have to calculate it manually.
=> fix(widget-recents): fetch proper to user avatar in direct spaces

Jenkinsfile
Syncs us with the SDK publish token from Jenkins.
=> chore(Jenkinsfile): use sdk shared publish token

packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-spaces/src/helpers.js, packages/node_modules/@ciscospark/widget-message/src/helpers.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/listeners.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.test.js, packages/node_modules/@ciscospark/widget-recents/src/helpers.js, packages/node_modules/@ciscospark/widget-recents/src/helpers.test.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
When fetching a group of spaces, we only need to store the user data from the "to user" in a one-on-one conversation. The recents widget does not need any other data in the redux store, ie: other participants and space activities. 
I've also split out `fetchSpacesEncrypted` from `fetchSpaces` to make things more readable.
=> Remove storing of activities and users in fetch spaces

Jenkinsfile.tab
TAB tests are failing due to the old nvm install command.
=> chore(tab): don't install nvm on tab tests

packages/node_modules/@ciscospark/spark-widget-base/src/styles.css, packages/node_modules/@ciscospark/widget-recents/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/styles.css
Okay I need you guys to bear with me:
It's not possible to fully customize the scrollbars in IE11. there are some **non-standard** properties offered by MS that allows developers to only customize certain properties (mostly color related props). Unfortunately, we can not set the width of the scrollbar in IE11 using CSS (it could be done with other tools such as jQuery). I need your feedback for at least on space widget if you want it **with** or **without** arrows or what colors). I will share what  we had before and what we have changed them into:
=> feat(widgets):Semi-customized the scrollbar styling on IE11

packages/node_modules/@ciscospark/widget-recents/src/components/NoSpaces.css, packages/node_modules/@ciscospark/widget-recents/src/components/NoSpaces.js, packages/node_modules/@ciscospark/widget-recents/src/components/NoSpaces.test.js, packages/node_modules/@ciscospark/widget-recents/src/components/__snapshots__/NoSpaces.test.js.snap, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/messages.js, test/journeys/lib/test-helpers/recents-widget/index.js, test/journeys/specs/smoke/widget-recents/index.js
Fix bug where recents widget would get stuck on the loading spinner for a user with no spaces + implement no spaces design.
The CSS is borrowed from the web client to make sure we're in line with their design -- if y'all want any changes just let me know.
There is currently no better way to handle the no spaces SVG as our usual icon component can only handle SVGs with one path, not two. Collab-ui doesn't currently have an icon for it, either.
=>  fix(widget-recents): recents widget does not load for user with no spaces

packages/node_modules/@ciscospark/widget-recents/src/container.js
The previous code would fire events to redux with every mouse scroll.
This changes so that it only updates the store when the `isScrolledToTop` actually changes.
=> feat(widget-recents): update scroll status as needed

packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.js
Avatars and people were not being loaded properly because the `encryptedSpaces` object wasn't being passed properly.
One too many `.thens` in the code
=> fix(widget-recents): load space avatars properly

Jenkinsfile
file "gitcommit" that gets archived with the build as well. When the production push job gets done, it will update the commit from the "gitcommit" file with the git tag "production". That way, the TAP tests can check out "production" before running.
=> chore(Jenkins): add gitcommit file to archives

Jenkinsfile.tab, Jenkinsfile.tap
NPM test users is no longer private and we do not need to add the npm token.
=> chore(tab/tap): removing npm credentials/git checkout

scripts/utils/package.js
The build for es/npm is failing due to sass issues in the widget demo. Since widget demo isn't on npm, this is a short term fix to stop building the demo and other demos for npm.
=> chore(scripts): filter demo from get widget script

.circleci/config.yml
There seems to be issues when circle runs the integration tests at the same time on different browsers. It could be purely coincidence, but this seems to have passed easier.
=> chore(circleci): run journey tests serially to reduce timeouts

packages/node_modules/@ciscospark/widget-space/README.md, packages/node_modules/@ciscospark/widget-space/SETUP.md, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/errors.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-space/src/messages.js, test/journeys/lib/test-users.js, test/journeys/specs/recents/dataApi/basic.js, test/journeys/specs/smoke/multiple/index.js, test/journeys/specs/smoke/widget-recents/index.js, test/journeys/specs/smoke/widget-space/index.js, test/journeys/specs/space/data-api.js, test/journeys/specs/space/index.js, test/journeys/specs/space/startup-settings.js, test/journeys/specs/tap/widget-space/space.js, test/journeys/testplan.md
This PR introduces two breaking changes to the space widget:
* The previously deprecated legacy destination props of "toPersonEmail", "toSpace", "toPersonId" are no longer supported.
* Destination types of "SPACEID" and "USERID" require the fully encoded hydra ID to be able to look up these destinations via federation.
=> Destination ID Hydra Requirements

test/journeys/lib/test-helpers/space-widget/main.js, test/journeys/specs/tap/widget-space/oneOnOne.js, test/journeys/specs/tap/widget-space/space.js
Tap tests were failing due to them not being updated with the hydraid support for space destination. This PR converts the TAP tests to using the test user helper methods for space and user creation.
There are also some optimizations added due to animations not being disabled on the production server. This was causing click events to not register properly because the activity menu was not fully animated away before the click was attempted.
=> Fixing tap tests for stability and hydra support

test/journeys/lib/browser.js, test/journeys/specs/smoke/widget-recents/index.js, test/journeys/specs/smoke/widget-space/index.js
Adding more stability features to smoke tests that get run on PRs. 
Calling tests on Firefox run from circle to sauce are flaky at best. We have chosen to skip the calling tests for now until the meetings plugin can be utilized which gives better firefox support.
=> test(journeys): add delay for test user propagation to smoke tests

.circleci/config.yml
Fix the build path error that prevents the widgets
demo from running on the live sample.
This pull request addresses the current issue with the public demos not containing the correct script to allow them to operate successfully.
Fixes # (issue)
SPARK-101841
Please delete options that are not relevant.
=> chore(circle-ci): live demos missing script

.circleci/config.yml
Tap tests are timing out. Extend the circle no output timeout.
Test result circle build: https://circleci.com/gh/webex/react-widgets/10484?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
=> chore(circle): extend timeout for tap test

packages/node_modules/@ciscospark/react-component-utils/src/constants.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/messages.js, packages/node_modules/@ciscospark/widget-message/src/translations/en.js
Description of changes made (Required)
* Added code to get a notification same as 'web client' when the message contains an adaptive card
For example:
* When a message only contains an adaptive card  with /without an image in it (without normal images )then notification be 'Responded with a card /Responded with {number} cards'
* Message contains both adaptive card and normal images then the notification is 'Shared a photo /Shared {number} photos'
Associated issue number/tracking link (Required)
[94107](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-94107)
**The following criteria should be met (Required)**
- [] Tests have been added for new functionality and all existing tests pass.
Reviewers (Required)
@InteractiveTimmy @akoushke
=> Support notifications for adaptive cards

packages/node_modules/@ciscospark/widget-space/src/actions.js, packages/node_modules/@ciscospark/widget-space/src/actions.test.js, packages/node_modules/@ciscospark/widget-space/src/constants.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/errors.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/setup.test.js, packages/node_modules/@ciscospark/widget-space/src/index.js, packages/node_modules/@ciscospark/widget-space/src/selector.js, packages/node_modules/@ciscospark/widget-space/src/selector.test.js
When using a destination type of email and the destination ID is mixed case, convert to lowercase to match the response from the server.
Also added a missing test suite around the `setup.js` file of the space widget. This caused me to have to move the constants into its own file due to jest trying to load reselect when doing `import X from './'`.
Commits should be separated and easy to follow.
=> FIX: Widget Space Email Setup

packages/node_modules/@webex/spark-widget-base/README.md, packages/node_modules/@webex/spark-widget-base/src/enhancers/withBrowserGlobals.js, packages/node_modules/@webex/spark-widget-base/src/enhancers/withDataAPI.js, packages/node_modules/@webex/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@webex/widget-meet/src/index.html, packages/node_modules/@webex/widget-meetings/src/index.html, packages/node_modules/@webex/widget-recents-demo/src/components/demo-widget-recents/index.js, packages/node_modules/@webex/widget-recents/README.md, packages/node_modules/@webex/widget-recents/src/index.html, packages/node_modules/@webex/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@webex/widget-space/README.md, packages/node_modules/@webex/widget-space/create-space-widget-with-server.md, packages/node_modules/@webex/widget-space/src/index.html, test/journeys/server/multiple.html, test/journeys/server/production/recents.html, test/journeys/server/production/space.html, test/journeys/server/recents.html, test/journeys/server/space.html
Builds off of #1045 and should be rebased once merged in. 
Changes the `window.ciscospark` implementation to `window.webex`.
=> 'Webex' browser global namespace

packages/node_modules/@webex/react-component-adaptive-card/src/adaptiveCard.scss
Due to an issue caused by [this change](https://github.com/webex/react-widgets/blob/7974b2ba141ea1ef38180218a1730ad094866866/packages/node_modules/%40ciscospark/react-component-adaptive-card/src/adaptiveCard.scss#L1), the non-componentized momentum library was being pulled in and causing global styles to be overridden.
=> fix(adaptive-card): use proper momentum library

packages/node_modules/@webex/redux-module-media/src/actions.js
A missed object in the webex rename was found causing meeting issues with the widget.
=> fix(media): use proper webex object

packages/node_modules/@webex/react-component-video/src/index.js
React prints an error message with using the non-camel-cased version of `playsInline`.
=> fix(video): use proper react property naming

packages/node_modules/@webex/widget-space/src/selector.js
Widget space was expecting the mercuryStatus object to be a regular javascript object and not an immutable object. 
It was caught in a loop that constantly was attempting to connect to mercury every time a store updated: https://github.com/adamweeks/react-widgets/blob/207c9c79c74c67f0661edef1f3b29d7c304c4b25/packages/node_modules/@webex/widget-space/src/enhancers/setup.js#L64-L69
=> fix(widget-space): convert mercuryStatus to js object

SCRIPTS.md, package-lock.json, package.json
The "colors" package was being provided as a sub-dependency, but after removing the "es-check" package, "colors" was gone.
Adding it back in since it is a specific dependency.
=> Fix broken build

packages/node_modules/@webex/redux-module-teams/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/redux-module-teams/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@webex/redux-module-teams/src/actions.js, packages/node_modules/@webex/redux-module-teams/src/actions.test.js, packages/node_modules/@webex/redux-module-teams/src/reducer.js, packages/node_modules/@webex/redux-module-teams/src/reducer.test.js
As part of the investigation into 429 error handling, it was discovered that we are not storing the error from the teams convo endpoint which has the highest rate of 429 errors of most endpoints.
This will be a step towards being able to respond to 429 errors.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-129689
=> feat(r-m-teams): add support for error handling

packages/node_modules/@webex/redux-module-media/src/actions.js
I noticed we have unit test only for the functions that dispatch an action in `redux-module-media/src/actions.js` so I didn't add unit test for this new function.  This is just a helper function to automatically set `audio` and `video` constraints before calling `placeCall`.
I'm having a hard time to test it locally since it needs https to have access to the `navigator.mediaDevices` object and its methods. 
Is it possible to deploy it to Netlify and test it before we merged it?
=> feat(webex): set audio and video dynamically to calls in widgets

scripts/webpack/webpack.dev.babel.js
Having the widgets serve on `0.0.0.0` did a disservice to developers trying to use media since we don't serve over https and browsers will block media access to anything not "localhost" served over http.
=> chore(webpack): serve on localhost [skip ci]

packages/node_modules/@webex/widget-demo/src/components/demo-widget/index.js
During a request in the ask space, I noticed the composer actions config isn't in the example code in the samples. Added here:
=> feat(widget-demo): add composer actions to example

packages/node_modules/@webex/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/redux-module-spaces/src/actions.js
The scope of the changes in this pull request is adding explicit error details to the already implemented fix for [this case](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-132963). This will allow users to see an explicit messaged in the view based on the data retrieved from the JS SDK.
=> fix(redux-module-spaces): add code to error message

packages/node_modules/@webex/react-redux-spark-fixtures/src/__fixtures__/spark.js, packages/node_modules/@webex/react-redux-spark/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/react-redux-spark/src/__snapshots__/component.test.js.snap, packages/node_modules/@webex/react-redux-spark/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@webex/react-redux-spark/src/actions.js, packages/node_modules/@webex/react-redux-spark/src/actions.test.js, packages/node_modules/@webex/react-redux-spark/src/component.js, packages/node_modules/@webex/react-redux-spark/src/reducer.js, packages/node_modules/@webex/react-redux-spark/src/reducer.test.js, packages/node_modules/@webex/widget-space/src/container.js
This PR handle the issue mentioned on this ticket: Ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-147741
Basically when we "Remove Widget" we also make sure that we remove (DELETE) the device.
Steps to test it: 
1) Add you Access Token
2) In the "Space Widget" section click on "Open Space Widget"
3) Open the Developer console and go to the "Network" tab 
4) Click on "Remove Widget"
5) You should see a DELETE call to `https://wdm-a.wbx2.com/wdm/api/v1/devices/<<devideId>>`
=> Unregister device when removing widget

.circleci/config.yml
Disable TAP tests until engineering team has coverage to support.
=> chore(circle): disable tap testing

scripts/webpack/webpack.dev.babel.js
Changes to the CSP spec have made definitions without a protocol match the protocol of the requested page instead of a wildcard. We need to be explicit on the protocol the connection is made to. 
This will match an update to the [developer portal documentation](https://developer.webex.com/docs/widgets#content-security-policy) as well.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-142925
=> chore(webpack): update the dev server CSP

.github/ISSUE_TEMPLATE/config.yml
This will disallow issues to be opened on Github but give users links for help.
=> docs: add issue links

packages/node_modules/@webex/react-container-message-composer/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/components/ComposerButtons.js, packages/node_modules/@webex/react-container-message-composer/src/components/ComposerButtons.test.js, packages/node_modules/@webex/react-container-message-composer/src/components/__snapshots__/ComposerButtons.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/index.test.js
- Avoid multiple widgets in the DOM opening the same input element
=> fix(message-composer): use unique id for input

packages/node_modules/@webex/react-component-activity-text/src/styles.css
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-153362
The css spacing didn't match the web client and desktop clients for paragraphs and blocks.
Pre Changes Widget:
Web Client:
Mac Client:
Post PR Widget:
=> feat(ActivityText): add block padding

packages/node_modules/@webex/react-container-message-composer/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/components/ComposerButtons.js, packages/node_modules/@webex/react-container-message-composer/src/components/__snapshots__/ComposerButtons.test.js.snap
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180467
We did some strange things to get momentum icon buttons to work, but this solution is easier and works across browsers.
=> fix(MessageComposer): use icon as label for file input

packages/node_modules/@webex/react-component-utils/src/constants.js, packages/node_modules/@webex/react-component-utils/src/files.js, packages/node_modules/@webex/react-component-utils/src/files.test.js, packages/node_modules/@webex/react-container-message-composer/src/container.js, packages/node_modules/@webex/widget-message/src/container.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-172895
We were checking for large files upon clicking the attach button, but drag and drop was not using the same check.
=> Add Drag and Drop file size limit

packages/node_modules/@webex/react-component-md-text-input/src/index.js
**Description of changes made** 
* User can enter value for zero `maxLength` of the `input.text` element(https://adaptivecards.io/explorer/Input.Text.html)
**Associated issue number/tracking link**  
[SPARK-124705](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-124705)
=> fix(card-element):  enter input value for zero length of text element

packages/node_modules/@webex/react-component-adaptive-card/src/adaptiveCard.scss
**Description of changes made (Required)**
* Neither `FactSet` nor `fact` has a wrap parameter, but [factset config](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config#schema-factsetconfig) uses `wrap:true` by default.
**Associated issue number/tracking link (Required)**
[SPARK-180138](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180138)
**Relevant screenshots to UI (Optional)**
**Before bug fix:**
**After:**
=> fix(card-css): wrap fact value text

test/journeys/specs/smoke/widget-space/index.js, test/journeys/specs/tap/widget-space/oneOnOne.js
There are numerous known issues with the meet widget currently.
This will disable the e2e tests for meet widget until SPARK-143533 is complete.
=> test(journey): disable meet widget tests

packages/node_modules/@webex/widget-recents/src/enhancers/setup.js, packages/node_modules/@webex/widget-recents/src/enhancers/setup.test.js
Removing the secondary space load due to the default limit and hard coded 25 being the same amount.
This also makes the first spaces request follow the limit passed in params.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-217484
=> feat(widget-recents): load requested number of spaces

packages/node_modules/@webex/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@webex/redux-module-conversation/src/reducer.js, packages/node_modules/@webex/widget-files/src/selectors.js
Files widget wasn't updated with the proper area to find convo activities after the thread feature was added.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-212342
=> Display content from threads in files widget

packages/node_modules/@webex/widget-roster/src/styles.css
Fixes an issue where part of the native scrollbar in the participant list gets hidden when there are external participants.
=> fix(widget-roster): people tab scrollbar fix

packages/node_modules/@webex/private-react-component-space-destination/src/index.js, packages/node_modules/@webex/redux-module-users/src/actions.js, packages/node_modules/@webex/webex-widget-base/src/enhancers/withCurrentUser.js, packages/node_modules/@webex/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@webex/widget-message/src/container.js, packages/node_modules/@webex/widget-space/src/container.js
Adding a prop so that users may disable the presence feature of the Space widget. Disabling presence could optimize widget load time, as there will be less APIs to call.
=> Add ability to turn off presence

.circleci/config.yml
No new breaking changes with v3 of the orb, they're updating their internal tooling and cleaning up some code
https://github.com/CircleCI-Public/aws-s3-orb/pull/23
=> chore(): upgrade s3 circleci orb to v3

packages/node_modules/@webex/react-component-activity-item-base/src/styles.css
Changed metadata color from #666:
to #545454 according to figma spec:
[SPARK-219857](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219857)
=> fix(style): update metadata color

packages/node_modules/@webex/react-component-activity-item-base/src/styles.css
Changed from:
To:
according to [SPARK-219840](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219840)
=> fix(style): reduce spacing between meta and message

packages/node_modules/@webex/react-component-activity-item/src/styles.css
Reduced thread border thickness from 4px to 2px and added border radius according to figma.
From: 
To:
=> fix(style): reduce thread border thickness

packages/node_modules/@webex/react-redux-spark/src/component.js, packages/node_modules/@webex/react-redux-spark/src/sdk.js, packages/node_modules/@webex/react-redux-spark/src/sdk.test.js
Proxy SDK allows us to track metrics from SDK instances that are created outside the widget.
=> fix(react-redux-spark): add proxy to existing sdk

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Description:  Added changes that if the speed dial's phone type already in use and added headerText for Form
The below image describes that all the speed dial's phone types are in use
=> fix(inUse): InUse Changes

packages/node_modules/@webex/widget-call-history/src/CallHistory.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.types.ts
Sending makeCall function from Main repository to 2nd repository(react-widgets project) as a prop.
This codes fixes that When refreshing the re-design landing page, cross launch token going as empty when trying to make call from Call History List
=> fix(CHMakeCallchanges): CH Make Call Changes

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/utils/voiceOver.ts, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Description:
- Disabling audio and video buttons if the voicemail address is not available
- Need to use the same style as we use on caller name to the phone number/address when there is no name present for both Call-history and Voicemail features
=> fix(VMnullCheck): Voicemail null check fix

packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
[Jira link](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-449693)
Dialpad: Currently, shift-tab from the number key goes to the previous number in numerical order. When shift - tab from any number button, it should go back to the search field.
=> fix(dialpadissue): fixed focus on search input

packages/node_modules/@webex/webex-sign-in-page/src/WebexSignInPage.scss
MS Themes support for Dark Mode, High Contrast, Default
Changed the color of "click here" and "Grant Permission" text as per the figma to support the themes
Jira link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-420824
=> fix(darkTheme): signIn Ui changes

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
**Description:** This PR provides a fix for the issue where the 'selected' state does not get cleared after moving the cursor outside of a row or clicking outside the row. The solution was achieved by removing the 'OnPress' method from both the call history and voicemail sections.
Jira link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-488831
=> fix(VMandCHRowSelected): fixed CH and VM row selected issue

packages/node_modules/@webex/webex-sign-in-page/src/WebexSignInPage.scss
As per the IVY comments updated the hyperlink color and font weight.
https://www.figma.com/file/Mh170f6uvIf3bs1HeeFLXu/MS-int.-themes?node-id=20%3A344&mode=dev
=> fix(darktheme): darktheme hyper link color updated

packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.styles.scss, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx
**Description:** This pull request addresses a styling conflict caused by the .md-loading-spinner-wrapper class being used globally across multiple components. The global nature of this class resulted in unintended side effects on components outside of the voicemail feature. To resolve this issue, the .md-loading-spinner-wrapper class has been nested within the .vmLoader class, ensuring that its styles are applied exclusively to the voicemail feature.
=> Scope .md-loading-spinner-wrapper to vmLoader Class for Voicemail Feature Isolation

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
It was required that ,once a speed dial is added or exiting the dialog, focus should be back to the speed dial section where the plus/add button is located, have provided a fix for this behavior.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503867](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-503867)
=> fix(focusissue): focussing back for accessibility

packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx, packages/node_modules/@webex/widget-number-pad/src/utils/WebexDialPad.ts
Handled long press on 0 and * from Dialpad, which will allow  the use of the '+' symbol by long-pressing '0' and ',' symbol by long-pressing '*' on the Dialpad in plugin for MS Teams.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-517897](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-517897)
=> fix(dialpad): allow longpress for '0' and '*'

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.types.tsx
Provided a fix for the problem where if a reordered item is focused once again it is announcing the text which was set when the text was set after reorder is complete and not the actual text which it should announce when focused.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-520895](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-520895)
=> fix(voiceover): reordered item voiceover text not reinitializing

packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsItem.tsx
Dial pad had two issues (screenshots attached in the below Jira):
1. Empty address for a few directory contacts.
2. Empty object created without an address for a few contacts. 
Both issues are addressed as part of this PR.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-509710
=> fix(dialpad): empty address fix

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
add commas/breaks between announcements? (e.g., “Started rearranging XYZ Work, Use arrow keys to adjust position, Press Space again to stop rearranging, etc...)
=> fix(voiceover): add breaks between announcements

packages/node_modules/@webex/widget-call-history/src/CallHistory.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.types.ts
**Jira**: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-452240
**by making the following changes**
In the MSFT client side, when a user clicks on any call history record  or audio/video button, the missed call notification badge/counter should dismiss.
=> fix(callHistory): badge counter

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/ScrubbingBar.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.styles.scss, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx
Description:
This PR includes changes for Windows, Mac, and web platforms.
Call History Changes:
1. Voiceover for displayed time and date of the call.
2. Voiceover for outgoing and incoming call information.
3. Instructions on how to focus on action buttons.
Voicemail Changes:
1. Voiceover for unread voicemails represented with an icon.
2. Instructions on how to focus on action buttons.
3. Media seek slider now announces the correct role and label. Previously, it had a confusing label and value 
4. focus was lost once the Play button was activated.
5. Media seek slider is missing a visible focus outline
Jira's Link
**Win** - Recent Calls: JAWS: The displayed time and date for the calls are not conveyed
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526782
**Win** - Recent Calls: JAWS: …
=> fix(spark:526782): callhistory item aria lable for date and time

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx
Create a speed dial form previously allowed 10 to 12 characters. Now it will allow 10 to 15 characters.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-533233](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-533233)
=> fix(speeddial):Teams Integration: Create Speeddial limited to 12 characters.

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/ScrubbingBar.tsx
Description: **isFocusVisible** from **useFocusRing** is consistently returning false even when the thumb is focused.
Instead of relying on isFocusVisible, we can handle focus and blur by using focus state.
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526771
=> fix(SPARK-526771): Media seek slider focus

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/utils/dateUtils.ts, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Description:
This PR contains voiceover announcements for the call history date and in the voicemail. If there is no data, a comma should not be added
Vidcast link
https://app.vidcast.io/share/ea4598fd-1090-42d8-800f-ea0b1f62c053
=> fix(spark:526772): callhistory date annuouncement

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx
This PR is to change regex, used for validation check of phone number in speed dial add and edit.
1) Will not limit the length of numbers in the speed dial input field. There will be a minimum length of 1.
2) Allow special chars to be saved in between the numbers. (this is for example used when dialing into Webex meetings or other IVR-based systems. That interacts with DTMF tones. e.g. "," would insert 2sec pause")
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-535963](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-535963)
=> fix(speeddial): phone number regex change

packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Jira link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526745
Description: Web - Voicemail: Screen Readers: Blue dot indicating unread message is not announced
This PR includes the aria-label and role
=> fix(SPARK-526745): screen reader for blue dot indication

packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
Win - Dial Pad: JAWS: Dial pad does not announce grouping relationship
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526781](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526781)
**The group label and role, i.e. 'Dial pad, group', should be announced only when the first number in the dial pad is focused.
Ensure the rest of the dial pad numbers are announced without ‘Dial pad, group’ as e.g.: ‘[focused number], button’**
=> fix(voiceover): Win - Dial Pad: JAWS: Dial pad does not announce grouping relationship

packages/node_modules/@webex/widget-call-history/src/utils/voiceOver.ts, packages/node_modules/@webex/widget-voice-mail/src/ScrubbingBar.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx
This pr consists of changes required to announce role, label and value when it is focused and when slider is moved arrow keys current time stamp will be announced.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526743?src=confmacro](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526743?src=confmacro)
=> fix(voicemail): Media seek slider announces no role and voiceover

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
Description: Showing the draggable icon (the icon with 6 dots) on focus as it is done on hover, so the KB user is aware that the items can be rearranged.
=> SPARK-526800 - KB: No instructions on how to reorder the speed dial list

packages/node_modules/@webex/react-container-message-composer/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/components/ComposerButtons.js, packages/node_modules/@webex/react-container-message-composer/src/components/__snapshots__/ComposerButtons.test.js.snap
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539198 
Problem: The Choose a file button in the chat panel doesn't visually appear, focusable using the Tab key, and selectable using the Enter key to choose a file so the user cannot identify the functionality of the control.
Fix: Added the Button element to bring the keyboard focus for the input element used to attach files.
=> fix(spacewidget): add focus to the attach file button

packages/node_modules/@webex/react-component-chip-file/src/styles.css, packages/node_modules/@webex/react-component-confirmation-modal/src/styles.css, packages/node_modules/@webex/react-container-message-composer/src/mentions.css
* Currently in the react messages widget, the file upload thumbnail subtitle was failing the colour contrast test.
* The colour was too light and not dark enough.
* Code has been added to modify the CSS class colour of that subtitle to the required one (as given by Applause)
* **Currently could not really write tests for this. Hence marking PR as a draft**
[SPARK-549502](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549502)
[SPARK-550132](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-550132)
[SPARK-550133](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-550133)
Original             	   |  Fixed
:-------------------------:|:-------------------------:
**<img width="499" alt="Screenshot 2024-08-08 at 11 37 02 AM" src="https://github.com/user-attachments/assets/acf87bce-5016-43d2-b40 …
=> Fixed Chat Color Contrast: Light grey file size text fails contrast

packages/node_modules/@webex/react-component-activity-share-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-share-file/src/index.js, packages/node_modules/@webex/react-component-activity-share-files/src/styles.css, packages/node_modules/@webex/react-component-activity-share-thumbnail/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-share-thumbnail/src/index.js
This PR addresses the issue of download buttons not being accessible. The download buttons can be accessed through `Shift + Tab` but the image files' Download button was not accessible.
- To fix it, we have disabled the `hover` ability of the Image component rather show the file name and downlaod button by default. This makes the download button present to be accessible by doing `Shift + Tab`
- Additionally, I've added the file names along with the download button's aria-label so that it doesn't simply read Download but rather what to download.
https://github.com/user-attachments/assets/bcbca58d-c9a1-4d6b-8142-36254226edba
=> fix(ActivityShare): accessibility for download buttons

packages/node_modules/@webex/react-component-activity-item-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-item-base/src/index.js, packages/node_modules/@webex/react-component-activity-item-base/src/styles.css, packages/node_modules/@webex/react-component-confirmation-modal/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-confirmation-modal/src/index.js, packages/node_modules/@webex/react-component-confirmation-modal/src/index.test.js, packages/node_modules/@webex/react-container-activity-list/src/__snapshots__/index.test.js.snap
* Currently, in the react widgets when we have focus on the messages it does not show the action items and only shows them on hover.
* This is an issue for users on mobile and desktop as they cannot access these items nor do they have instructions to observe them.
* When we click on 'delete', the dialog window was also not keyboard focusable.
* Code has been added so that the buttons are now visible and focusable when the message gets focus.
* The navigation is as expected in desktop and should be in mobile browsers as well (currently testing this). This clears the Applause requirements.
* The dialog window is now keyboard focusable.
[SPARK-549503](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549503)
[SPARK-550134](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-550134)
=> React Widgets: Fixed message action buttons not showing on hover and key order

packages/node_modules/@webex/react-component-presence-avatar/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-presence-avatar/src/index.js, packages/node_modules/@webex/react-container-activity-list/src/__snapshots__/index.test.js.snap
Problem
Currently, in the react widgets when the message seen by a person who dont have profile pic then we show avatar with light grey and black letters which is not as per accessibility standards.
Fix
configured Avatar so that the Avatar is dark grey and letters are white color
JIRA
[[SPARK-549500](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-549500)
=> fix(spacewidget): updated color contrast of avatar component

packages/node_modules/@webex/react-container-message-composer/src/mentions.css
* Currently, we had fixed an earlier issue regarding text colour for the message placeholder text as per - [SPARK-550132](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-550132).
* However, the contrast test was still failing due to the transparency of the text.
* Added CSS to remove the text transparency.
###JIRA
[SPARK-550132](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-550132)
Original             	   |  Fixed
:-------------------------:|:-------------------------:
**<img width="421" alt="Screenshot 2024-08-30 at 9 34 40 AM" src="https://github.com/user-attachments/assets/9ccef6e2-108c-4e90-982a-f378b967c6f2">**  |  **<img width="421" alt="Screenshot 2024-08-30 at 9 35 09 AM" src="https://github.com/user-attachments/assets/43cd2e13-3084-4048-8dd4-07fba1dadffe">**
=> Fixed transparency issue in react widgets

packages/node_modules/@webex/react-component-activity-text/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-text/src/index.js, packages/node_modules/@webex/react-component-activity-text/src/index.test.js, packages/node_modules/@webex/react-container-activity-list/src/formatters/at-mention.js
**Problem:**
When the space widget is loaded inside of an iframe, the links in the messages when clicked are restricted from being loaded.
**Solution:**
Add target="_blank" attribute to open these links in a new tab
JIRA: SPARK-556112
=> fix(space-widget): links in messages should open in new tab

.github/workflows/pull-request.yml
In GitHub actions we weren't checking out to the respective PR's commits. The pipeline was running on the base branch.
This was happening because we wernt checking out the code correctly
Added the 'with' tag in checkout steps in github actions
- Create a dummy branch (base node-upgrade) and made the same changes on that branch- 
- Raised a PR against that branch and confirmed the github actions whether we are checking out the correct commit or not.
Dummy branch -https://github.com/webex/react-widgets/tree/test-github-actions
Dummy PR - https://github.com/webex/react-widgets/pull/1447 ( This PR has all the change from yarn workspace PR also)
Github actions for the above PR https://github.com/webex/react-widgets/actions/runs/11551753036
=> fix(tooling): checkout-in-github-actions

packages/node_modules/@webex/react-component-activity-share-files/src/styles.css
Problem: In the 'Content' tab, many elements such as the 'Download', 'Remove', and 'Flag' buttons are focusable with the keyboard and screen reader which are not related to the 'Content' tab as they belong to the 'Message' tab.
JIRA: [SPARK-564416](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-564416)
Solution: I have fixed this issue by changing the visibility of the class="md-content__hover" to inherit, previously we are using visible value for the visibility CSS property, due to this elements from the Message tab is visible inside the Content and People tab.
Vidcast: https://app.vidcast.io/share/aa1703c9-66ce-407b-84f5-d882605ae3d3
=> fix(fcc): fix focusing unnecessary elements inside Content tab.

packages/node_modules/@webex/widget-meet/src/components/call-active/index.js
This change updates the tabIndex values for meeting controls to ensure proper keyboard navigation and accessibility.
Previously, after focusing on the "Leave Meeting" button, focus did not move correctly to the next element
By explicitly setting all controls to tabIndex={0}, they are now included in the tab order and can be navigated consistently using the keyboard.
This improves accessibility by providing a proper focus order across all meeting controls
https://app.vidcast.io/share/11e734ac-9ab7-4498-9245-74f4090b1193
< ENUMERATE TESTS PERFORMED, WHETHER MANUAL OR AUTOMATED >
---
=> fix(space-widget): The focus order widget logic for in meeting
