webex/react-widgets

packages/node_modules/@ciscospark/react-container-activity-list/src/selectors.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js
Fix issue where we create blank activity items in the activity list for items where we don't have rendering built.
=> fix(react-container-activity-list): Add whitelist for activity types

package.json, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/widget-meet/src/actions.js, packages/node_modules/@ciscospark/widget-meet/src/components/call-active/index.js, packages/node_modules/@ciscospark/widget-meet/src/components/call-active/styles.css, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-meet/src/reducer.js
Add ability to drag self view around active video.
=> feat(widget-meet): Draggable self view

src/basic-demo.js, src/demo-login/index.js, src/demo-login/styles.css, src/demo-widget-message-meet/index.js, src/demo-widget-message-meet/styles.css, src/example-code/index.js
Changing the widget demo to have a better UX for auth flow
=> feat(demo): better demo flow

packages/node_modules/@ciscospark/react-container-message-composer/src/container.js, packages/node_modules/@ciscospark/react-container-message-composer/src/index.test.js, packages/node_modules/@ciscospark/redux-module-activity/src/actions.js
Went ahead and prefixed the activity module as well.
=> fix(redux-module-activity): clear typing indicator when sending activity

packages/node_modules/@ciscospark/react-component-title-bar/src/styles.css, packages/node_modules/@ciscospark/widget-meet/src/components/call-active/styles.css, packages/node_modules/@ciscospark/widget-meet/src/components/call-inactive/styles.css, packages/node_modules/@ciscospark/widget-meet/src/components/call-incoming/styles.css, packages/node_modules/@ciscospark/widget-meet/src/styles.css, packages/node_modules/@ciscospark/widget-message-meet/src/styles.css, packages/node_modules/@ciscospark/widget-message-meet/src/styles/main.css
Fix issues with global rules on page causing elements in widget to mis-align.
=> styles: Add global border box, and flex box styles

packages/node_modules/@ciscospark/widget-base/src/index.js, packages/node_modules/@ciscospark/widget-message-meet/README.md, packages/node_modules/@ciscospark/widget-message-meet/src/actions.js, packages/node_modules/@ciscospark/widget-message-meet/src/container.js, packages/node_modules/@ciscospark/widget-message-meet/src/data-api.js, packages/node_modules/@ciscospark/widget-message-meet/src/reducer.js, packages/node_modules/@ciscospark/widget-message-meet/src/root.js, packages/node_modules/@ciscospark/widget-message-meet/src/store.js
Allows for multiple stores and widgets on a single page.
Adds `remove` method for widget cleanup.
=> feat(widget-message-meet): Allow multiple widgets and removal

Jenkinsfile, packages/node_modules/@ciscospark/widget-message/src/container.js
- Fix to not allow message composer into view until we can send a message
- Update jenkins to not build all packages, since we're not publishing everything to cdn
=> fix(widget-message): Hide composer until loaded, jenkins change

packages/node_modules/@ciscospark/widget-message/src/container.js
Fix issue where we try to create a conversation gets created before device is registered
=> fix(widget-message): Wait for device registration before createconvo

packages/node_modules/@ciscospark/react-redux-spark/src/spark.js
=> chore(react-redux-spark): silence the logger in production

Jenkinsfile
=> fix(tooling): Point to correct CDN location

packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/widget-base/src/constructor.js, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-message-meet/src/container.js
Fix for uncaught errors when onEvents fires in actions.
=> fix(widget-base): Fix onEvent calling

src/demo-widget-message-meet/index.js, src/token-input/index.js, src/token-input/styles.css
Removing the ability to get access token via oauth from the demo for the time being. It stopped working a while ago anyway.
I feel like the way it is implemented is causing some issues having two different spark instances. Would like to revisit when we have more time.
=> fix(demo): removing oauth from demo

README.md, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/widget-meet/src/constants.js, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-message-meet/README.md, packages/node_modules/@ciscospark/widget-message-meet/src/container.js, packages/node_modules/@ciscospark/widget-message-meet/src/event-names.js, packages/node_modules/@ciscospark/widget-message/src/constants.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-space/README.md, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/event-names.js
Update docs to add new eventing, and also add ability to pass eventNames as props.
=> feat(widget-space): Space and WMM events update

packages/node_modules/@ciscospark/widget-recents/src/container.js
=> fix(widget-recents): Fix space click bug

packages/node_modules/@ciscospark/react-component-title-bar/src/styles.css, packages/node_modules/@ciscospark/react-container-message-composer/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/styles.css
Message composer also had the same issue
=> Space title overflow

Jenkinsfile
we can revert this after this is released:
https://github.com/callemall/material-ui/pull/6847
=> chore: install specific version of recompose so demo works

packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-media/src/reducer.js, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-meet/src/styles.css, packages/node_modules/@ciscospark/widget-message-meet/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/styles.css
Some style fixes to make it look prettier
=> fix(widget-meet): Fix webrtc detection in safari

package.json, packages/node_modules/@ciscospark/react-component-spinner/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-spinner/src/index.js, packages/node_modules/@ciscospark/react-component-spinner/src/index.test.js, packages/node_modules/@ciscospark/react-component-spinner/src/styles.css, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/styles.css, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
Bugfixes and optimizations from SSDK-720 and others.
Also, welcome `prop-types`!
=> Recents Updates

Jenkinsfile, packages/node_modules/@ciscospark/widget-recents-demo/package.json, packages/node_modules/@ciscospark/widget-recents-demo/src/components/demo-widget-recents/index.js, packages/node_modules/@ciscospark/widget-recents-demo/src/components/demo-widget-recents/styles.css, packages/node_modules/@ciscospark/widget-recents-demo/src/components/token-input/index.js, packages/node_modules/@ciscospark/widget-recents-demo/src/index.html, packages/node_modules/@ciscospark/widget-recents-demo/src/index.js, packages/node_modules/@ciscospark/widget-recents/src/styles.css
=> Recents demo

packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-item/src/index.js, packages/node_modules/@ciscospark/react-component-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-post/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-post/src/index.js, packages/node_modules/@ciscospark/react-component-activity-post/src/index.test.js, packages/node_modules/@ciscospark/react-component-activity-share-files/src/index.js, packages/node_modules/@ciscospark/react-component-activity-text/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-text/src/index.js, packages/node_modules/@ciscospark/react-component-activity-text/src/index.test.js, packages/node_modules/@ciscospark/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/redux-module-activity/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-activity/src/actions.js
This should fix our html cleaning issue and match closely with what the clients have in place.
We filter both on outgoing and anything we set dangerously in incoming.
Will need to create a config option to pass the filtered values in a configurable way.
=> fix(widget-message): Fix html filter

packages/node_modules/@ciscospark/react-component-ringtone/src/index.js
Fixes this specific CSP issue for calling
=> fix(react-component-ringtone): Add try/catch for creating audio

LICENSE, README.md
Update README format, correct Table of Contents, and add License information
Add LICENSE file
=> docs(general): update README and LICENSE

packages/node_modules/@ciscospark/react-redux-spark/src/spark.js, scripts/webpack/webpack.dev.babel.js
Do not merge until: #236 is merged
=> feat(widget-base): Add multi tab/window support

packages/node_modules/@ciscospark/react-component-error-display/src/styles.css, packages/node_modules/@ciscospark/redux-module-errors/package.json, packages/node_modules/@ciscospark/redux-module-errors/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-errors/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-errors/src/actions.js, packages/node_modules/@ciscospark/redux-module-errors/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-errors/src/index.js, packages/node_modules/@ciscospark/redux-module-errors/src/reducer.js, packages/node_modules/@ciscospark/redux-module-errors/src/reducer.test.js, packages/node_modules/@ciscospark/widget-space/src/actions.js, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/messages.js, packages/node_modules/@ciscospark/widget-space/src/reducer.js, packages/node_modules/@ciscospark/widget-space/src/selector.js, packages/node_modules/@ciscospark/widget-space/src/styles.css
Was considering going with the injectErrors way that you did metrics. Thoughts on this store method compared to it?
=> Display error for no connection

package.json, scripts/webpack/webpack.base.babel.js
=> refactor(tooling): Remove libpng requirement

scripts/webpack/webpack.dev.babel.js
So that we can catch any csp issues if something changes.
=> chore(tooling): Add csp to webpack dev server

packages/node_modules/@ciscospark/widget-space/src/reducer.js
This is a patch for a Proxy issue
=> refactor(widget-space): convert to object for spaceDetails

packages/node_modules/@ciscospark/widget-message/src/events.js, test/journeys/lib/hydra.js, test/journeys/specs/messageMeet/widget-message-meet/meet.js, test/journeys/specs/messageMeet/widget-message-meet/messaging.js, test/journeys/specs/oneOnOne/meet.js, test/journeys/specs/oneOnOne/messaging.js, test/journeys/specs/space/messaging.js
Doing some detailed tests on the events that arrive and their data structure.
=> Event data - actorName and tests expanded

packages/node_modules/@ciscospark/widget-message-meet/src/components/activity-menu/index.js, packages/node_modules/@ciscospark/widget-message-meet/src/components/activity-menu/styles.css, packages/node_modules/@ciscospark/widget-space/src/styles.css, scripts/webpack/webpack.base.babel.js
Ended up only fixing the specific issue. Main issue is that we're passing classes down into components which breaks css modules.
=> fix(widget-space): Button style collision

packages/node_modules/@ciscospark/react-component-activity-text/src/styles.css
Matches what web client is doing for newlines within one message.
=> feat(react-component-activity-text): add pre-wrap style for new lines

Jenkinsfile.tap
Needed to fix failing tap tests.
=> fix(tooling): Add node 7 install to tap tests

package.json
=> chore(package): update @ciscospark/eslint-config to version 2.0.1

packages/node_modules/@ciscospark/widget-space/src/messages.js
Error message change as requested by Meeta.
=> feat(widget-space): update space not found message

Jenkinsfile.tap
This should force a retry on any type of error and also attach failure logs to the body
=> chore(tooling): Add try...catch retry to Tap Tests

packages/node_modules/@ciscospark/react-component-activity-list/src/index.js, packages/node_modules/@ciscospark/react-component-confirmation-modal/src/styles.css, packages/node_modules/@ciscospark/react-component-list-separator/src/styles.css, packages/node_modules/@ciscospark/react-component-new-messages-separator/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-new-messages-separator/src/index.js, packages/node_modules/@ciscospark/react-component-new-messages-separator/src/index.test.js, packages/node_modules/@ciscospark/react-component-new-messages-separator/src/styles.css, packages/node_modules/@ciscospark/react-container-activity-list/src/index.js, packages/node_modules/@ciscospark/widget-message/src/container.js
Also threw in a refactor to remove react-intl requirement in a component since we already had the message defined.
=> Fix css global

Jenkinsfile.jssdk, package.json, scripts/utils/jssdkversion.js, scripts/utils/update.js
We'll use this script as part of the js-sdk post deploy jenkins script.
=> chore: add spark upgrade script

packages/node_modules/@ciscospark/react-component-activity-item-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-item-base/src/index.js, packages/node_modules/@ciscospark/react-component-activity-item-base/src/styles.css, packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-menu/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-menu/src/styles.css, packages/node_modules/@ciscospark/react-component-activity-post/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-files/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-text/src/styles.css, packages/node_modules/@ciscospark/react-component-avatar/src/styles.css, packages/node_modules/@ciscospark/react-component-button-controls/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-button-controls/src/styles.css, packages/node_modules/@ciscospark/react-component-button/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-button/src/index.js, packages/node_modules/@ciscospark/react-component-button/src/styles.css, packages/node_modules/@ciscospark/react-component-incoming-call/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-list-separator/src/styles.css, packages/node_modules/@ciscospark/react-component-title-bar/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-title-bar/src/index.js, packages/node_modules/@ciscospark/react-component-title-bar/src/styles.css, packages/node_modules/@ciscospark/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-message-composer/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/styles.css
https://voxeolabs.atlassian.net/browse/SSDK-823
=> Ui fixes for space widget

package.json
=> chore(package): add husky for precommit and prepush tests

packages/node_modules/@ciscospark/widget-recents/events.md, packages/node_modules/@ciscospark/widget-recents/src/events.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
I've created a build from this PR. Should we go through the full release process or point it at `develop`?
=> feat(widget-recents): add toPersonEmail to event data

packages/node_modules/@ciscospark/react-component-title-bar/src/styles.css
Long titled rooms would shrink the avatar in title bar.
=> style(react-component-title-bar): add avatar no shrink style

packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js
=> fix(widget-recents): Remove no-enter keypresses for selecting space

packages/node_modules/@ciscospark/react-hoc-conversation-mercury/package.json, packages/node_modules/@ciscospark/react-hoc-conversation-mercury/src/index.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.test.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/reducer.js
✅ Automation tests for widget-space pass
=> feat(react-hoc-conversation-mercury): refactor mercury conversation events

jest.config.json, package.json, packages/node_modules/@ciscospark/react-container-file-downloader/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-redux-spark/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-errors/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-features/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/redux-module-flags/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-presence/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-presence/src/reducer.test.js, packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/reducer.test.js.snap
=> chore(package): update jest to version 21.1.0

packages/node_modules/@ciscospark/react-container-message-composer/src/container.js, packages/node_modules/@ciscospark/redux-module-activity/src/actions.js, packages/node_modules/@ciscospark/redux-module-activity/src/actions.test.js
Added debounce and added checks for sending userTyping messages to server.
=> fix(react-container-message-composer): Improve typing performance

package.json
=> fix(package): update react-dropzone to version 4.1.3

scripts/utils/build.js
=> fix(tooling): Fix babel preset es2015

package.json, packages/node_modules/@ciscospark/react-component-icon/src/index.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.test.js, packages/node_modules/@ciscospark/redux-module-search/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/redux-module-search/src/index.js, packages/node_modules/@ciscospark/redux-module-search/src/index.test.js, packages/node_modules/@ciscospark/widget-roster/src/components/add-participant/index.js, packages/node_modules/@ciscospark/widget-roster/src/components/add-participant/styles.css, packages/node_modules/@ciscospark/widget-roster/src/container.js, packages/node_modules/@ciscospark/widget-roster/src/selector.js
This uses hydra for ALL email search, regardless of team.
=> Roster search email

packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/reducer.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/styles.css, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, test/journeys/specs/space/dataApi/basic.js, test/journeys/specs/space/global/basic.js
=> Feature: Incremental decrypt

test/journeys/specs/tap/widget-recents/index.js, test/journeys/specs/tap/widget-space/space.js
=> test(journeys): add silent logging to tap tests

packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-space/src/selector.js
Should alleviate decline call journey test errors, and exceptions during widget load.
=> Fix: tap test stability

packages/node_modules/@ciscospark/react-component-activity-item-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-menu/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-post-action/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-post/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-files/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-thumbnail/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-add-file-button/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-avatar/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-button/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-chip-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-chip-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-file-staging-area/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-icon/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-icon/src/index.js, packages/node_modules/@ciscospark/react-component-icon/src/styles.css, packages/node_modules/@ciscospark/react-component-incoming-call/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-scroll-to-bottom-button/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-file-uploader/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-message-composer/src/__snapshots__/index.test.js.snap
This is to fix a bug from the s4d portal implementation
=> fix(react-component-icon): use specific classname

packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/styles.css, packages/node_modules/@ciscospark/widget-recents/src/components/spaces-list/index.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/reducer.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, test/journeys/lib/test-helpers/recents-widget/index.js, test/journeys/specs/recents/dataApi/basic.js, test/journeys/specs/recents/global/basic.js
https://voxeolabs.atlassian.net/browse/SSDK-1351
=> Recents group calling

packages/node_modules/@ciscospark/react-component-textarea/src/styles.css, packages/node_modules/@ciscospark/react-container-message-composer/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-message-composer/src/container.js, packages/node_modules/@ciscospark/react-container-message-composer/src/index.test.js, packages/node_modules/@ciscospark/react-container-message-composer/src/mentions.css, packages/node_modules/@ciscospark/react-container-message-composer/src/styles.css, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/styles.css
Using the auto-grow feature of react-mentions to grow the text area even for users without the mentions flag enabled.
=> Growing textarea

test/journeys/specs/oneOnOne/dataApi/features.js, test/journeys/specs/oneOnOne/global/features.js, test/journeys/specs/space/dataApi/startup-settings.js, test/journeys/specs/space/featureFlags.js
feature flags have been defaulted to `true`, we need to manually set these flags to false to verify they still work
=> test(journeys): add specific false feature flags

packages/node_modules/@ciscospark/widget-space/README.md
- update Space Widget features list
=> Update Space Widget Features

package.json, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/messages.js, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/messages.js
Gracefully handle failures for get/create conversations and display the error message in the widget.
=> Conversation failure handling

packages/node_modules/@ciscospark/react-container-read-receipts/src/selectors.js
add sort so typing participants get priority
=> feat(react-container-read-receipts): typing participants priority

packages/node_modules/@ciscospark/widget-base/src/store.js
Utilizing the serialize immutable method for better view on the store with the browser plugin
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize
=> feat(widget-base): update redux devtools implementation

packages/node_modules/@ciscospark/widget-recents/src/container.js
we were listening to the wrong event
=> fix(widget-recents): delete incoming call when connected

packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-list/src/index.js, packages/node_modules/@ciscospark/react-component-activity-system-message/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-system-message/src/index.js, packages/node_modules/@ciscospark/react-component-activity-system-message/src/index.test.js, packages/node_modules/@ciscospark/react-component-activity-system-message/src/messages.js, packages/node_modules/@ciscospark/react-component-call-data-activity/package.json, packages/node_modules/@ciscospark/react-component-call-data-activity/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-call-data-activity/src/helpers.js, packages/node_modules/@ciscospark/react-component-call-data-activity/src/index.js, packages/node_modules/@ciscospark/react-component-call-data-activity/src/index.test.js, packages/node_modules/@ciscospark/react-component-call-data-activity/src/messages.js, packages/node_modules/@ciscospark/react-container-activity-list/src/helpers.js, packages/node_modules/@ciscospark/react-container-activity-list/src/selectors.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js, packages/node_modules/@ciscospark/widget-recents/src/components/spaces-list/index.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js
=> Fix recents call data and use shared component

packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/helpers.js
Resolves https://voxeolabs.atlassian.net/browse/SSDK-1609
=> Fix read events triggering widget events

Jenkinsfile, Jenkinsfile.jssdk, Jenkinsfile.tap
This change will append and reset the project's npmrc file instead of the home directory's one which was causing issues on jenkins.
=> chore(jenkins): use project npmrc file

packages/node_modules/@ciscospark/widget-demo/README.md, packages/node_modules/@ciscospark/widget-demo/package.json, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/styles.css, packages/node_modules/@ciscospark/widget-demo/src/components/token-input/index.js, packages/node_modules/@ciscospark/widget-demo/src/components/token-input/styles.css, packages/node_modules/@ciscospark/widget-demo/src/index.html, packages/node_modules/@ciscospark/widget-demo/src/index.js
This will be useful for the netlify deploys. I don't plan on putting it on the cdn unless asked specifically.
=> feat(widget-demo): initial package

packages/node_modules/@ciscospark/widget-message/src/container.js
Apparently flagging messages was broken along with deleting messages. No more!
=> fix(widget-message): activities are no longer an immutable object

Jenkinsfile
Missed adding the resource URL to the manifest. This should fix it.
=> fix(tooling): Add build URL to SRI

packages/node_modules/@ciscospark/react-component-error-display/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/enhancers/errors.js, packages/node_modules/@ciscospark/widget-space/src/messages.js
=> No destination error

packages/node_modules/@ciscospark/redux-module-activity/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-activity/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-activity/src/helpers.js, packages/node_modules/@ciscospark/redux-module-activity/src/helpers.test.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js
I have another ticket to switch to the commonmark module that the web client is now using.
=> Fix message parsing and conversion

packages/node_modules/@ciscospark/react-component-people-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-people-list/src/__snapshots__/list-item.test.js.snap, packages/node_modules/@ciscospark/react-component-people-list/src/index.js, packages/node_modules/@ciscospark/react-component-people-list/src/index.test.js, packages/node_modules/@ciscospark/react-component-people-list/src/list-item.js, packages/node_modules/@ciscospark/react-component-people-list/src/list-item.test.js, packages/node_modules/@ciscospark/widget-roster/src/selector.js
also a quick fix on the roster selector
=> People List - display email on hover

package.json, packages/node_modules/@ciscospark/react-component-activity-share-thumbnail/src/index.test.js, packages/node_modules/@ciscospark/react-component-typing-indicator/src/index.test.js, packages/node_modules/@ciscospark/react-container-activity-list/src/index.test.js, packages/node_modules/@ciscospark/react-container-message-composer/src/index.test.js, packages/node_modules/@ciscospark/react-redux-spark/src/component.test.js, packages/node_modules/@ciscospark/react-redux-spark/src/inject-spark.test.js
=>  chore(package): update jest to version 22.1.2

packages/node_modules/@ciscospark/react-component-activity-share-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-file/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-file/src/styles.css
=> style(react-component-activity-share-file): add overflow for file name

packages/node_modules/@ciscospark/react-container-activity-list/src/selectors.js, packages/node_modules/@ciscospark/react-container-activity-list/src/selectors.test.js, packages/node_modules/@ciscospark/react-container-message-composer/src/reducer.js, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js, packages/node_modules/@ciscospark/widget-roster/src/components/external-participant/index.js, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/activity-menu.js, scripts/tests/openh264.js
eslint update didn't catch these, but now they are throwing errors.
=> chore(all): apply eslint fixes

packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-spaces/src/helpers.js, packages/node_modules/@ciscospark/widget-recents/src/components/space-item/index.js
Matches how the web client sanitizes the response from conversation
=> Fix space empty activity

packages/node_modules/@ciscospark/redux-module-activity/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/container.js
[SSDK-1770](https://voxeolabs.atlassian.net/secure/RapidBoard.jspa?rapidView=81&projectKey=SSDK&view=detail&selectedIssue=SSDK-1770)
=> fix(widget-message): Fix unhandled exception when adding invalid files

packages/node_modules/@ciscospark/redux-module-flags/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-flags/src/actions.js, packages/node_modules/@ciscospark/redux-module-flags/src/actions.test.js, packages/node_modules/@ciscospark/widget-message/src/container.js
[SSDK-1775](https://voxeolabs.atlassian.net/secure/RapidBoard.jspa?rapidView=81&projectKey=SSDK&view=detail&selectedIssue=SSDK-1775)
=>  fix(widget-module-flags): Prevent multiple flagging calls

packages/node_modules/@ciscospark/react-container-activity-list/src/selectors.js, packages/node_modules/@ciscospark/redux-module-activity/src/__snapshots__/helpers.test.js.snap, packages/node_modules/@ciscospark/redux-module-activity/src/helpers.js, packages/node_modules/@ciscospark/redux-module-activity/src/helpers.test.js
Specific fix for [SSDK-1777](https://voxeolabs.atlassian.net/browse/SSDK-1777)
Note: there are still differences in rendering, but that can't really be addressed until we change to a different markdown renderer.
=> fix: Add filter to remove extra new lines

packages/node_modules/@ciscospark/widget-meet/src/enhancers/withMeetDetails.js
Fix for [SSDK-1794](https://voxeolabs.atlassian.net/browse/SSDK-1794)
=> fix(widget-meet): Use userId when fetching avatar for direct space

packages/node_modules/@ciscospark/react-container-message-composer/src/container.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/widget-message/src/selector.js
fix(widget-message): Incorrect events payload
fix(react-container-message-composer): Proptypes error from mention lib
=> fix: Small fixes for failing 

packages/node_modules/@ciscospark/redux-module-activity/src/helpers.test.js
https://voxeolabs.atlassian.net/browse/SSDK-1776
=> Fix url markdown

packages/node_modules/@ciscospark/react-component-utils/src/uuid-utils.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.test.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-meet/src/enhancers/withCallHandlers.js, packages/node_modules/@ciscospark/widget-meet/src/enhancers/withCallMemberships.js, packages/node_modules/@ciscospark/widget-meet/src/enhancers/withToType.js, packages/node_modules/@ciscospark/widget-meet/src/events.js, packages/node_modules/@ciscospark/widget-message/src/events.js, packages/node_modules/@ciscospark/widget-recents/src/events.js, packages/node_modules/@ciscospark/widget-space/src/selector.js
currently `toPersonId` param only supports uuid due to sdk limitation, this will convert it before sending over to sdk.
=> feat: to person hydra id support for conversation

packages/node_modules/@ciscospark/widget-meet/src/enhancers/withCallHandlers.js, packages/node_modules/@ciscospark/widget-meet/src/index.html, packages/node_modules/@ciscospark/widget-meet/src/reducer.js
The incoming call handler is done with the media enhancer which already
is being used by the meet widget.
=> fix(widget-meet): remove duplicate incoming call handler

.gitignore, packages/node_modules/@ciscospark/widget-space/src/selector.js, packages/node_modules/@ciscospark/widget-space/src/selector.test.js
- Uses ID instead of email for 1:1 conversations
- Adds test
- Removes unused function 
Resolves https://jira-eng-gpk2.cisco.com/jira/browse/SSDK-1851
=> Fix 1:1 conversation title

Jenkinsfile
It looks like packages may have been locked on the last run. This copies the config into the home directory to ensure the project config is maintained before adding the new token.
=> Fix NPM static analysis

Jenkinsfile, package.json, scripts/tooling/commands/check-testable.js, scripts/tooling/index.js, scripts/utils/git.js, scripts/utils/wrap-handler.js
Could use a review on the `Jenkinsfile`. Most of this is taken from the js-sdk. I've verified the node scripts work properly.
=> Skip ci feature for tooling

test/journeys/specs/tap/widget-recents/index.js
Production tap tests weren't updated with the current selectors for react virtualized.
=> test(tap): fix tap recents selectors

scripts/utils/publish.js
=> chore(tooling): fix publish from dry run

packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/messages.js
=> Recents Widget - Use Webex loading component

packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/messages.js
Builds on #782 and will be rebased once merged.
=> feat(widget-space): use new webex teams loading screen

.circleci/config.yml, Jenkinsfile, Jenkinsfile.jssdk, Jenkinsfile.tab, Jenkinsfile.tap
=> chore(tooling): change npm token env var

.babelrc, package-lock.json, packages/node_modules/@ciscospark/redux-module-activities/src/helpers.js, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-meet/src/index.js, packages/node_modules/@ciscospark/widget-meet/src/selector.js, packages/node_modules/@ciscospark/widget-space/src/actions.js, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/index.js, packages/node_modules/@ciscospark/widget-space/src/selector.js
This enables sip calling and will allow us to call TP units.
In order for this to fully work, the developer will need to disable all other `spaceActivities` besides `meet`.
=> feat(widget-space): enable sip calling

packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space/README.md, packages/node_modules/@ciscospark/widget-space/SETUP.md, packages/node_modules/@webex/private-react-component-space-destination/src/index.js, packages/node_modules/@webex/private-react-component-space-destination/src/styles.css
=> feat(widget-demo): add sip calling

package-lock.json, package.json
=> chore(package): update yargs to version 12.0.1

packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/helpers.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/helpers.js, packages/node_modules/@ciscospark/redux-module-conversation/src/helpers.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, scripts/webpack/webpack.dev.babel.js
The shape of the giphy activity as received from the server needs a bit of a massage to get it to play friendly with the `download()` function.
=> Add giphy activities support for conversation

package-lock.json, packages/node_modules/@ciscospark/redux-module-media/src/actions.js, packages/node_modules/@ciscospark/widget-meet/src/enhancers/withCallHandlers.js, packages/node_modules/@ciscospark/widget-meet/src/selector.js
There must have been some sort of issue when rebasing that happened after testing.
=>  fix call and call error handling

Jenkinsfile, package.json, scripts/publish/commands/widgets.js, scripts/utils/package.js
This will start publishing `widget-space` and `widget-recents` to npm as an installable package.
=> Publish widgets to npm

.circleci/config.yml
greenkeeper will now automatically update lockfiles for non-private repo
=> chore(circle): remove greenkeeper lockfile updates

packages/node_modules/@ciscospark/react-container-message-composer/src/actions.js, packages/node_modules/@ciscospark/redux-module-activities/package.json, packages/node_modules/@ciscospark/spark-widget-base/src/enhancers/withInitialState.js, packages/node_modules/@ciscospark/widget-space/src/events.js, scripts/build/commands/transpile.js, scripts/build/commands/widgets.js, scripts/utils/build.js, scripts/webpack/webpack.transpile.babel.js
After our initial publish of the widgets to npm, there were some issues in the generated output.
=> Various fixes to support npm export

.circleci/config.yml, Jenkinsfile, packages/node_modules/@ciscospark/react-component-chip-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-chip-base/src/index.js, packages/node_modules/@ciscospark/react-component-chip-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-file-staging-area/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-container-file-uploader/src/__snapshots__/index.test.js.snap, test/journeys/lib/test-helpers/index.js, test/journeys/lib/test-helpers/space-widget/meet.js, test/journeys/lib/test-users.js, test/journeys/specs/recents/dataApi/basic.js, test/journeys/specs/recents/global/basic.js, test/journeys/specs/smoke/multiple/index.js, test/journeys/specs/smoke/widget-recents/index.js, test/journeys/specs/smoke/widget-space/index.js, test/journeys/specs/space/data-api.js, test/journeys/specs/space/guest.js, test/journeys/specs/space/index.js, test/journeys/specs/space/startup-settings.js, test/journeys/testplan.md, wdio.conf.js
Primarily using the newly creating test users helper functions to reduce the amount of code in our journey test setup.
=> Journey Test Refactors

packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js
Space demo is broken due to incorrect handling of destination mode changes.
=> fix(space-demo): handle mode change

scripts/webpack/webpack.base.babel.js, scripts/webpack/webpack.transpile.babel.js
woff files from collab-ui were being converted with improper typings
=> chore(webpack): remove failing woff conversion

packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space/README.md, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/activity-menu.js, packages/node_modules/@ciscospark/widget-space/src/styles.css, packages/node_modules/@webex/private-react-component-space-destination/src/index.js
Closes #884 and rebased on master.
=> Space widget `secondaryActivitiesFullWidth` prop

Jenkinsfile
Journey tests have moved to circle CI and are required to pass before a merge can happen.
=> chore(Jenkinsfile): remove journey tests

packages/node_modules/@ciscospark/spark-widget-base/src/enhancers/withInitialState.js
https://github.com/zalmoxisus/redux-devtools-extension#usage
=> chore(spark-widget-base): update redux devtools name

Jenkinsfile, packages/node_modules/@ciscospark/react-redux-spark/src/spark.js, scripts/webpack/webpack.base.babel.js, scripts/webpack/webpack.dev.babel.js
This should fix the "unable to downscope token" console messages.
=> feat(spark): add client id and scope

packages/node_modules/@ciscospark/react-component-activity-menu-header/src/styles.css, packages/node_modules/@ciscospark/react-component-confirmation-modal/src/styles.css, packages/node_modules/@ciscospark/react-component-list-separator/src/styles.css, packages/node_modules/@ciscospark/widget-space/src/styles.css
remove all CSS variables as a workaround for IE11 compatibility
=> style(widget-space): remove css variables

packages/node_modules/@ciscospark/react-component-presence-avatar/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-presence-avatar/src/index.js, packages/node_modules/@ciscospark/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-title-bar/src/styles.css
=> Title Bar - Vertically Center Avatar

packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js
Copying and pasting demo code fails
=> fix(widget-demo): correct spaceActivities prop

.circleci/config.yml, package-lock.json, package.json, wdio.conf.js
Updated some configs with retries and removed the ports from circle since we are using different VMs for firefox and chrome tests. 
Also upgraded to the latest version of sauce-service.
=> chore(circle): remove sauce connect hard coded ports

packages/node_modules/@ciscospark/react-component-presence-avatar/src/index.js, packages/node_modules/@ciscospark/react-container-presence-avatar/src/index.js, packages/node_modules/@ciscospark/redux-module-users/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-users/src/actions.js, packages/node_modules/@ciscospark/redux-module-users/src/actions.test.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-recents/README.md, packages/node_modules/@ciscospark/widget-recents/events.md, packages/node_modules/@ciscospark/widget-recents/src/components/RecentsHeader.css, packages/node_modules/@ciscospark/widget-recents/src/components/RecentsHeader.js, packages/node_modules/@ciscospark/widget-recents/src/components/RecentsHeader.test.js, packages/node_modules/@ciscospark/widget-recents/src/components/__snapshots__/RecentsHeader.test.js.snap, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/events.js, packages/node_modules/@ciscospark/widget-recents/src/reducer.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, packages/node_modules/@ciscospark/widget-recents/src/styles.css, packages/node_modules/@webex/react-component-spaces-list/src/index.js, test/journeys/lib/test-helpers/index.js, test/journeys/lib/test-helpers/recents-widget/index.js, test/journeys/specs/recents/global/startup-settings.js, test/journeys/specs/smoke/widget-recents/index.js, wdio.conf.js
Adds new config options to the recents widget: `enableAddButton` and `enableUserProfile`.
=> Recents Widget - Add user profile and add space to header

packages/node_modules/@ciscospark/react-component-presence-avatar/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-presence-avatar/src/index.js, packages/node_modules/@ciscospark/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-recents/README.md, packages/node_modules/@ciscospark/widget-recents/events.md, packages/node_modules/@ciscospark/widget-recents/src/components/RecentsHeader.css, packages/node_modules/@ciscospark/widget-recents/src/components/RecentsHeader.js, packages/node_modules/@ciscospark/widget-recents/src/components/UserProfileAvatar.css, packages/node_modules/@ciscospark/widget-recents/src/components/UserProfileAvatar.js, packages/node_modules/@ciscospark/widget-recents/src/components/UserProfileAvatar.test.js, packages/node_modules/@ciscospark/widget-recents/src/components/__snapshots__/RecentsHeader.test.js.snap, packages/node_modules/@ciscospark/widget-recents/src/components/__snapshots__/UserProfileAvatar.test.js.snap, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/errors.js, packages/node_modules/@ciscospark/widget-recents/src/events.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, test/journeys/lib/test-helpers/recents-widget/index.js, test/journeys/specs/recents/global/startup-settings.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-61527
=> User Profile Setting Menu

.circleci/config.yml, wdio.conf.js
Adding some preference flags seems to have done the trick, but firefox needed to use my webcam for some reason?
So draft for now to iron out tweaks and fix whatever I missed
=> Fix for firefox automation problems

packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/messages.js, packages/node_modules/@ciscospark/widget-space/src/container.js, packages/node_modules/@ciscospark/widget-space/src/messages.js, packages/node_modules/@webex/react-component-loading-screen/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-loading-screen/src/index.js, packages/node_modules/@webex/react-component-loading-screen/src/styles.css
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-62279
=> Removed Loading Messages and Minor changes on Loading Screen

Jenkinsfile.tab
tab tests are failing, but not due to tests, hopefully this fixes
=> chore(tab): update tab tests to match tap tests config

package-lock.json, package.json, packages/node_modules/@webex/react-component-loading-screen/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-loading-screen/src/index.js, packages/node_modules/@webex/react-component-loading-screen/src/index.test.js
The Img component will not render if the src is bad.
Which is sadly the case for npm installed widgets currently.
=> feat(loading-screen): use Img component to display images

packages/node_modules/@ciscospark/widget-recents/README.md, packages/node_modules/@ciscospark/widget-space/README.md
=> docs: remove jsx details

package-lock.json, package.json, packages/node_modules/@ciscospark/react-component-utils/src/uuid-utils.js, packages/node_modules/@ciscospark/react-redux-spark/src/spark.js, packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-spaces/src/helpers.js, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-recents/src/container.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-recents/src/enhancers/setup.test.js, packages/node_modules/@ciscospark/widget-recents/src/selector.js, test/journeys/specs/recents/global/startup-settings.js
Features added when basic mode is enabled:
* Spaces will be fetched from the hydra /rooms endpoint
* No decryption needed
Features removed for basic mode:
* No space avatars (hydra will be adding this feature to /rooms)
* No calling support (knowing when a space has a call)
* No Read/Unread status (spaces will always display as unread)
* No notification icons (cannot know when spaces are muted)
=> Recents Widget: add basicMode feature

rollup.config.js
Example output of one generated css:
```js
{  
"activityItem":"react-component-activity-item-base__activityItem__LmFjdGl2",
"published":"react-component-activity-item-base__published__LmFjdGl2",
"contentContainer":"react-component-activity-item-base__contentContainer__LmFjdGl2",
"pending":"react-component-activity-item-base__pending__LmFjdGl2",
"content":"react-component-activity-item-base__content__LmFjdGl2",
"meta":"react-component-activity-item-base__meta__LmFjdGl2",
"displayName":"react-component-activity-item-base__displayName__LmFjdGl2",
"avatarWrapper":"react-component-activity-item-base__avatarWrapper__LmFjdGl2",
"selfAvatar":"react-component-activity-item-base__selfAvatar__LmFjdGl2",
"error":"react-component-activity-item-base__error__LmFjdGl2", …
```
=> chore(rollup): scope css modules with component name

packages/node_modules/@ciscospark/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.js, packages/node_modules/@ciscospark/redux-module-spaces/src/actions.test.js
How to test: open and close the recents widget ~5 times to get 429'ed.
=> feat(r-m-spaces): add error when service fails

packages/node_modules/@ciscospark/widget-meet/src/components/call-inactive/index.js, packages/node_modules/@ciscospark/widget-meet/src/container.js, packages/node_modules/@ciscospark/widget-meet/src/messages.js, test/journeys/lib/test-helpers/space-widget/main.js, test/journeys/lib/test-helpers/space-widget/meet.js, test/journeys/lib/test-helpers/space-widget/messaging.js, test/journeys/specs/smoke/multiple/index.js, test/journeys/specs/smoke/widget-space/index.js, test/journeys/specs/space/startup-settings.js, test/journeys/specs/tap/widget-space/oneOnOne.js
Trying to stabilize tests, this PR helps, but I still had to retry MANY times to get calling tests to pass.
Merging this in is going to break TAP tests, should be resolved in SPARK-74070
=> Journey test call labels

packages/node_modules/@ciscospark/widget-demo/package.json, packages/node_modules/@ciscospark/widget-recents-demo/package.json, packages/node_modules/@ciscospark/widget-space-demo/package.json, scripts/build/commands/esm.js, scripts/utils/build.js, scripts/utils/package.js
We don't need to run builds on private packages that will not be available on NPM.
=> ESM Builds only non-private packages

packages/node_modules/@ciscospark/react-redux-spark/src/__snapshots__/component.test.js.snap, packages/node_modules/@ciscospark/react-redux-spark/src/component.js, packages/node_modules/@ciscospark/react-redux-spark/src/component.test.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-69846
=> Webex SDK Plugin check

scripts/build/commands/transpile.js
Fixing an eslint error changed the logic for the transpile handler, this PR will fix the command
=> fix(scripts): fix handler logic for transpiling all components

packages/node_modules/@ciscospark/widget-recents/README.md, packages/node_modules/@ciscospark/widget-space/README.md
Includes instructions on how to import the styles properly.
=> Add NPM guide to Widget READMEs

README.md, packages/node_modules/@ciscospark/spark-widget-base/README.md, packages/node_modules/@ciscospark/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@ciscospark/widget-recents-demo/src/components/demo-widget-recents/index.js, packages/node_modules/@ciscospark/widget-recents/README.md, packages/node_modules/@ciscospark/widget-space-demo/src/components/demo-widget-space/index.js, packages/node_modules/@ciscospark/widget-space/README.md
Found some more "Spark" references and updated links to the sdk.
=> docs: update spark references

package.json, packages/node_modules/@ciscospark/react-component-video/src/index.js
don't worry ill delete the 2nd commit
=> refactor(react-component-video): add playsinline attribute for webrtc

.circleci/config.yml, package.json
- add missing `'` to release script
- stop `run_all_tests` from running on master branch after merge
=> Pipeline fixes

.circleci/config.yml
I added those env vars to the circle ci web config and it worked, the only thing that wasn’t working was the version number export.
=> chore(circle): add aws vars

.circleci/config.yml
Version grepping solution via https://gist.github.com/DarrenN/8c6a5b969481725a4413
=> fix(circle): version number for cdn

.circleci/config.yml
User alpha/beta for latest and prerelease
=> Rename CDN links from latest+prerelease to alpha and beta

package-lock.json, package.json, packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-item/src/index.js, packages/node_modules/@ciscospark/react-component-activity-item/src/index.test.js, packages/node_modules/@ciscospark/react-component-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-list/src/index.js, packages/node_modules/@ciscospark/react-component-activity-list/src/index.test.js, packages/node_modules/@ciscospark/react-component-activity-share-files/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-files/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-files/src/index.test.js, packages/node_modules/@ciscospark/react-component-adaptive-card/package.json, packages/node_modules/@ciscospark/react-component-adaptive-card/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-adaptive-card/src/index.js, packages/node_modules/@ciscospark/react-component-adaptive-card/src/index.test.js, packages/node_modules/@ciscospark/react-component-utils/src/adaptiveCard.js, packages/node_modules/@ciscospark/react-component-utils/src/adaptiveCard.test.js, packages/node_modules/@ciscospark/react-component-utils/src/adaptiveCardUtil.js, packages/node_modules/@ciscospark/react-component-utils/src/adaptiveCardUtil.test.js, packages/node_modules/@ciscospark/react-component-utils/src/constants.js, packages/node_modules/@ciscospark/react-component-utils/src/index.js, packages/node_modules/@ciscospark/widget-message/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/widget-message/src/__snapshots__/selector.test.js.snap, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-message/src/enhancers/index.js, packages/node_modules/@ciscospark/widget-message/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-message/src/reducer.js, packages/node_modules/@ciscospark/widget-message/src/selector.js, packages/node_modules/@ciscospark/widget-message/src/selector.test.js
Description of changes made 
* Feature toggle for adaptive cards
* Rendering adaptive card
* Unit test case coverage
Associated issue number/tracking link 
[SPARK-94093](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-94093)
[SPARK-97152](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-97152)
Reviewers 
@adamweeks
=> feat : Render adaptive card behind feature toggle

packages/node_modules/@ciscospark/react-redux-spark/src/sdk.js, test/journeys/specs/smoke/widget-space/index.js
Webex SDK Config was accidentally changed.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-101565
=> fix: reenable spark-mention

packages/node_modules/@ciscospark/react-component-utils/src/uuid-utils.js, packages/node_modules/@ciscospark/react-component-utils/src/uuid-utils.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-users/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-users/src/actions.js, packages/node_modules/@ciscospark/widget-message/src/container.js, packages/node_modules/@ciscospark/widget-space/src/actions.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/errors.js, packages/node_modules/@ciscospark/widget-space/src/enhancers/setup.js, packages/node_modules/@ciscospark/widget-space/src/selector.js
- update validateAndDecodeId to use SDK
- use 'url' to load previous messages
=> fix(r-c-utils): update for federation

packages/node_modules/@ciscospark/react-component-activity-item/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-item/src/index.js, packages/node_modules/@ciscospark/react-component-activity-post/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-post/src/index.js, packages/node_modules/@ciscospark/react-component-activity-share-files/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-activity-share-files/src/index.js, packages/node_modules/@ciscospark/react-component-adaptive-card/src/__snapshots__/index.test.js.snap, packages/node_modules/@ciscospark/react-component-adaptive-card/src/index.js, packages/node_modules/@ciscospark/react-component-adaptive-card/src/index.test.js, packages/node_modules/@ciscospark/react-component-utils/src/adaptiveCardUtil.js, packages/node_modules/@ciscospark/react-component-utils/src/constants.js, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.js, packages/node_modules/@ciscospark/redux-module-conversation/src/actions.test.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.js, packages/node_modules/@ciscospark/redux-module-conversation/src/reducer.test.js
**Description of changes made (Required)**
- Changes in adaptive card utils file
- Changes in action and reducer files
**Associated issue number/tracking link (Required)**
[94095](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-94095)
**The following criteria should be met (Required)**
**Reviewers (Required)**
@adamweeks @InteractiveTimmy
=> feat(ac-utils):adaptive card actions

packages/node_modules/@webex/react-component-spaces-list/src/index.js, packages/node_modules/@webex/react-component-spaces-list/src/styles.css
This fix utilzes the suggestion at https://github.com/bvaughn/react-virtualized/issues/773
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-114717
=> fix(spaces-list): stop scrollbar flickering at certain sizes

test/journeys/lib/convo.js, test/journeys/specs/recents/global/basic.js
- Instead of using the convo id, accept the whole conversation object.
SPARK-108103 #done
=> test(journey): update helper funcs to use convo

CONTRIBUTING.md
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-128348
=> docs(Contributing): add build dependencies

packages/node_modules/@webex/react-component-utils/src/adaptiveCardUtil.js
**Description of changes made (Required)**
- Modified the AdaptiveCardUtils file to get selected element
- Jira ticket is related to the web client but the same bug found in widgets as well 
**Associated issue number/tracking link (Required)**
[SPARK-121774](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-121774)
**The following criteria should be met (Required)**
- [] Tests have been added for new functionality and all existing tests pass.
**Reviewers (Required)**
@adamweeks
=> feat(ac-util):fix select action

packages/node_modules/@webex/widget-meet/src/messages.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-138185
=> feat(widget-meet): rename spark references

packages/node_modules/@webex/widget-recents/README.md, packages/node_modules/@webex/widget-space/README.md
NPM install of widgets has not been beta for a while now 😃
=> docs: remove npm beta warning for widgets

package-lock.json, package.json, packages/node_modules/@webex/react-component-activity-item-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-menu-header/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-menu/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-share-file/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-share-thumbnail/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-chip-base/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-people-list/src/__snapshots__/list-item.test.js.snap, packages/node_modules/@webex/react-component-utils/src/__snapshots__/adaptiveCardUtil.test.js.snap, packages/node_modules/@webex/react-container-activity-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-container-message-composer/src/components/__snapshots__/ComposerButtons.test.js.snap, packages/node_modules/@webex/react-container-scrolling-activity/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/widget-recents/src/components/RecentsHeader.js, packages/node_modules/@webex/widget-recents/src/components/__snapshots__/RecentsHeader.test.js.snap, packages/node_modules/@webex/widget-recents/src/components/__snapshots__/UserProfileAvatar.test.js.snap
Description of changes made (Required)
* Upgraded the momentum UI react version 
* Updated the snapshots
Associated issue number/tracking link (Required)
[SPARK-136312](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-136312)
**The following criteria should be met (Required)**
Reviewers (Required)
@adamweeks
=> chore(package): update momentum-ui/react version to fix the multiselect of choiceset

packages/node_modules/@webex/react-component-activity-text/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-text/src/index.js, packages/node_modules/@webex/react-component-utils/src/activity.js, packages/node_modules/@webex/react-component-utils/src/activity.test.js, packages/node_modules/@webex/redux-module-activity/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/redux-module-activity/src/actions.js
This PR adds the ability to sanitize any text sent to the DOM from the activity post component.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-148479
=> Sanitize input before displaying

packages/node_modules/@webex/react-component-utils/src/constants.js, packages/node_modules/@webex/react-container-message-composer/src/container.js
=> feat(message-composer): add error for oversized attachments

.gitignore
Improperly ignoring all the files in our packages currently.
=> chore(gitignore): fix ignored packages

packages/node_modules/@webex/react-component-adaptive-card/src/adaptiveCard.scss, packages/node_modules/@webex/react-component-adaptive-card/src/index.js, packages/node_modules/@webex/react-component-adaptive-card/src/styles.css, packages/node_modules/@webex/react-component-md-choiceset-input/src/index.js, packages/node_modules/@webex/react-component-utils/src/adaptiveCardUtil.js, packages/node_modules/@webex/react-component-utils/src/constants.js, packages/node_modules/@webex/redux-module-conversation/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/redux-module-conversation/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@webex/redux-module-conversation/src/actions.js, packages/node_modules/@webex/redux-module-conversation/src/actions.test.js, packages/node_modules/@webex/redux-module-conversation/src/reducer.js
*Description of changes made (Required)*
* Added CSS changes
* Returns null when there is no input and no default value submitted for choice set
* Fix for disable the button and code-refactor for card action status and for button disability
*Associated issue number/tracking link (Required)*
[SPARK-180278](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180278)
[SPARK-180291](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180291)
=> fix(adaptive-card-bugs): bug fixes for cards

.circleci/config.yml
- enable TAP testing without paging
[SPARK-182163](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-182163) #done
=> chore: enable TAP tests

package-lock.json, package.json, packages/node_modules/@webex/react-component-md-choiceset-input/src/index.js, packages/node_modules/@webex/react-component-utils/src/__snapshots__/adaptiveCardUtil.test.js.snap, packages/node_modules/@webex/react-component-utils/src/adaptiveCardUtil.js, packages/node_modules/@webex/react-component-utils/src/adaptiveCardUtil.test.js
**Description of changes made**
* updated the version of adaptive cards
* added required changes for version update
* Added/removed test case
**Associated issue number/tracking link**
[SPARK-177455](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-177455)
=> chore(package): adaptive card version update

packages/node_modules/@webex/react-component-adaptive-card/src/adaptiveCard.scss, packages/node_modules/@webex/react-component-adaptive-card/src/index.js
**Associated issue number/tracking link (Required)**
[SPARK-183107](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-183107)
[SPARK-180284](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-180284)
**Relevant screenshots to UI (Optional)**
**For both wrap:true/false**
=> fix(text-block):markdown of text block

packages/node_modules/@webex/react-component-adaptive-card/src/adaptiveCard.scss
Jira ticket:
[SPARK-195767](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-195767)
=> fix(card):Small changes in adaptive card css

CONTRIBUTING.md, README.md, package.json, packages/node_modules/@webex/private-react-component-example-code/package.json, packages/node_modules/@webex/private-react-component-space-destination/package.json, packages/node_modules/@webex/private-react-component-space-destination/src/index.js, packages/node_modules/@webex/private-react-component-token-input/package.json, packages/node_modules/@webex/private-react-component-token-input/src/index.js, packages/node_modules/@webex/react-component-loading-screen/package.json, packages/node_modules/@webex/react-component-loading-screen/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-loading-screen/src/index.js, packages/node_modules/@webex/react-component-space-item/package.json, packages/node_modules/@webex/react-component-spaces-list/package.json, packages/node_modules/@webex/react-component-title-bar/package.json, packages/node_modules/@webex/widget-demo/src/components/demo-widget/index.js, packages/node_modules/@webex/widget-demo/src/index.html, packages/node_modules/@webex/widget-recents-demo/src/index.html, packages/node_modules/@webex/widget-recents/README.md, packages/node_modules/@webex/widget-recents/src/messages.js, packages/node_modules/@webex/widget-space-demo/src/index.html, packages/node_modules/@webex/widget-space/README.md, samples/recents-components/index.js, test/journeys/testplan.md
[SPARK-187174](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-187174)
=> Webex rebranding

packages/node_modules/@webex/react-component-utils/src/uuid-utils.js, packages/node_modules/@webex/redux-module-spaces/src/__snapshots__/actions.test.js.snap, packages/node_modules/@webex/redux-module-spaces/src/__snapshots__/reducer.test.js.snap, packages/node_modules/@webex/redux-module-spaces/src/actions.js, packages/node_modules/@webex/redux-module-spaces/src/actions.test.js, packages/node_modules/@webex/redux-module-spaces/src/helpers.js, packages/node_modules/@webex/redux-module-spaces/src/reducer.js, packages/node_modules/@webex/redux-module-spaces/src/reducer.test.js, packages/node_modules/@webex/widget-recents/src/events.js, packages/node_modules/@webex/widget-recents/src/selector.js, packages/node_modules/@webex/widget-space/src/actions.js, packages/node_modules/@webex/widget-space/src/enhancers/setup.js, test/journeys/lib/hydra.js
Fixes [SPARK-206010](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-206010)
=> Parse HydraId and store cluster information

.circleci/config.yml, package-lock.json, package.json
=> fix(package): update detective-es6

packages/node_modules/@webex/redux-module-spaces/src/actions.js, packages/node_modules/@webex/redux-module-spaces/src/helpers.js, packages/node_modules/@webex/widget-recents/src/selector.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-213899
Updates the the convo query string to a less rate limited query and more optimized for our use case.
=> Update convo list params for better rate limiting

packages/node_modules/@webex/react-component-people-list/src/styles.css, packages/node_modules/@webex/widget-roster/src/styles.css
[SPARK-215117](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-215117) #done
=> fix: enable scrolling of space roster

packages/node_modules/@webex/react-component-people-list/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-people-list/src/index.js, packages/node_modules/@webex/react-component-people-list/src/styles.css
- fix scrolling for lists that aren't controlled by React Virtualized
=> fix(r-c-people-list): fix scrolling for list

packages/node_modules/@webex/widget-space/src/container.js
[SPARK-223764](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223764)
=> Display timer when active in a meeting

packages/node_modules/@webex/widget-meet/src/enhancers/withCallHandlers.js, test/journeys/specs/space/startup-settings.js
I added a check for the sdkAdapter before placeCall
=> fix(widget-space): fixed startCall issue

packages/node_modules/@webex/react-component-title-bar/src/styles.css, packages/node_modules/@webex/widget-space/src/styles.css
Changed title and text color.
From: 
To:
=> chore(): update space widget header color

packages/node_modules/@webex/react-component-title-bar/src/styles.css
From:
To: 
Reference: [SPARK-219830](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-219830)
=> fix(style): change title text size and font

packages/node_modules/@webex/react-component-activity-item/src/styles.css
also simplified padding, and added border radius
=> reduced border size of thread

packages/node_modules/@webex/redux-module-media/src/actions.js, packages/node_modules/@webex/widget-recents/src/container.js
[SPARK-275103](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-275103)
=> Correctly grab conversationUrl from meetings payload

packages/node_modules/@webex/private-react-component-space-destination/src/index.js
[SPARK-312415](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312415)
Remove PSTN radio button from the demo page
=> remove PSTN option

packages/node_modules/@webex/widget-call-history/package.json
=> name updated in package json

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Added Missing Code from Voice mail and Call History
=> fix(widget-call-history) Added dataTestId

packages/node_modules/@webex/widget-number-pad/src/CallButtons/CallButtons.stories.tsx, packages/node_modules/@webex/widget-number-pad/src/CallButtons/CallButtons.tsx, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/CallSelectPopover.scss, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/CallSelectPopover.tsx, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsItem.scss, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsItem.tsx, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsList.styles.scss, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsListEmpty.tsx, packages/node_modules/@webex/widget-number-pad/src/hooks/useLazyLoadAvatarUrl.ts, packages/node_modules/@webex/widget-number-pad/src/hooks/useMakeCall.ts, packages/node_modules/@webex/widget-number-pad/src/index.ts, packages/node_modules/@webex/widget-voice-mail/src/hooks/useMakeCall.ts
Description:
1. Added Number Pad Changes
2. Added Make an Audio and Video Call Changes for Call History, Voicemail and Number Pad
=> fix(MakeCall) Make a call and Number Pad Changes

packages/node_modules/@webex/widget-voice-mail/src/hooks/useMakeCall.ts
Description:  Republishing Make Call
=> fix(MAKEACALL): Republish MakeCall

packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
fixed voice mail auto refresh issue
=> fix(VM): auto refresh voice mail bold unread issue

packages/node_modules/@webex/widget-call-history/src/CallHistory.tsx
Fixed Webex Call History missing field, callbackAddress
=> Fix(webex): WebexCalling Call Histrory callBack Address

package.json
Test PR to trigger a build in circle ci as we have added new Cilent Id and secret for prod env.
=> build: pr to trigger build in circle ci

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
Compatibility issue with Speed dial added in previous version
=> fix(SpeedDial): Compatibility issue

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx
Description:  Added call history avatar change
=> fix(avatarChange): avatar change

packages/node_modules/@webex/widget-number-pad/src/CallButtons/CallButtons.tsx
Issue 418905 - https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-418905
=> fix(Dialpad): Dialpad

packages/node_modules/@webex/widget-call-history/src/CallHistory.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Description:  Fixing CH Scrollbar Issue
=> fix(chScrollFix): CH Scroll Fix

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.styles.scss
Description:  Implemented the fix for speed dial scroll
=> fix(sdScrollFix): SDscroll fix

packages/node_modules/@webex/webex-sign-in-page/src/WebexSignInPage.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Added tooltip and style changes for speed dials
=> fix(speedDial): tooltip

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsItem.tsx, packages/node_modules/@webex/widget-number-pad/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/utils/avatarInitials.ts
Description:  Added Avatar Initials
=> fix(AvatarInitials): Avatar Initials

packages/node_modules/@webex/widget-call-history/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-number-pad/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-speed-dial/src/utils/avatarInitials.ts, packages/node_modules/@webex/widget-voice-mail/src/utils/avatarInitials.ts
=> fix(AvatarFix): Avatar Fix

packages/node_modules/@webex/widget-call-history/src/hooks/useMakeCall.ts, packages/node_modules/@webex/widget-call-history/src/utils/Logger.ts, packages/node_modules/@webex/widget-number-pad/src/hooks/useMakeCall.ts, packages/node_modules/@webex/widget-number-pad/src/utils/Logger.ts
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-427138
=> fix(makeAcall): make a call calling issue

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx
Description:  Added changes for Disabled Phone Types
=> fix(disablePhonetypes): Disable Phone Types

packages/node_modules/@webex/widget-number-pad/src/ContactCard/ContactCard.stories.tsx, packages/node_modules/@webex/widget-number-pad/src/ContactCard/ContactCard.styles.scss, packages/node_modules/@webex/widget-number-pad/src/ContactCard/ContactCard.tsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-429575
=> fix(contactCard): added contact card

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
Number of count of speed dial has increased to 20
=> fix(speedDial): SpeedDialsCount

package.json, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.styles.scss, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
Added changes for Delete Outlook Contact
=> fix(outlookDelete): Delete Outlook Contact Changes

package.json, packages/node_modules/@webex/webex-sign-in-page/package.json, packages/node_modules/@webex/widget-call-history/package.json, packages/node_modules/@webex/widget-number-pad/package.json, packages/node_modules/@webex/widget-speed-dial/package.json, packages/node_modules/@webex/widget-voice-mail/package.json
upgrading  @momentum-ui/react-collaboration version to "26.81.0"
=> fix(momemtumversion): upgrading momentumversion

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
Description:  Fixed the speed dial truncation issue and removed title from the Avatar tag because already there is a title at parent level in the speed dial item component
=> fix(sdTruncationFix): speeddial truncation fix

package.json, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.styles.scss, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Sip address pattern added with name and phone number margin adjust in call history and voicemail.
=> fix(speedDial): sipAddress

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/utils/voiceOver.ts, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Description:  
- Added aria labels for Call History.
- Created a new component called voiceOver specifically for handling announcement-related changes. 
- Implemented an additional condition for the voicemail avatar. Previously, the avatar was displayed based solely on the name. With the update, if a name is unavailable, we will use the avatar initials derived from the phone number.
=> fix(VM_Avatar_Fix): VM Avatar Fix with CH Voiceover Changes

packages/node_modules/@webex/webex-sign-in-page/src/WebexSignInPage.tsx
- added new prop clientType to detect if mobile is used
- added conditional class name based on client type
=> changed classname to handle mobile css

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx
**Enhance Speed Dial Menu Accessibility with Shift+F10 Keyboard Shortcut**
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466120
=> fix(contextmenu): Speed dial context menu issue

packages/node_modules/@webex/widget-call-history/src/CallHistory.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.types.ts, packages/node_modules/@webex/widget-call-history/src/utils/avatarInitials.ts
Feature development "hunt group and call queue" for redesign plugin call history tab.
=> fix(huntgroup_callqueue): feature

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Implement Drag-and-Drop Feature for Speed Dial Accessibility
Jira link: [https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466549](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466549)
=> fix(speeddialissue): dragNdrop issue

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx
The gap between name and phone number in call history records adjusted
=> fix(callHistory): gapIssue

packages/node_modules/@webex/webex-sign-in-page/src/WebexSignInPage.tsx
=> fix(loginImporvement): Login Improvement Changes

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Reverts webex/react-widgets#1347
=> Revert "fix(speeddialissue): dragNdrop issue"

packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Implement Drag-and-Drop Feature for Speed Dial Accessibility
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466549](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466549)
=> fix(speeddial): drag and drop windows issue

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Enhance Accessibility: Allow Navigating Speed Dial Contacts with Tab keys
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466144](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466144)
=> fix(speeddial): Fixed double tab issue

packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Reference PR : https://github.com/webex/react-widgets/pull/1361
Enhance Accessibility: Allow Navigating Speed Dial Contacts with Tab keys
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466144](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-466144)
=> fix(speeddial): Allow Navigating Speed Dial Contacts with Tab keys

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
Added aria labels to support voiceover for accessibility on speed dial items, speed dial context menu and for drag and drop.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-512677](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-512677)
=> feat(speeddial): Voiceover Accessibility for Speed Dial items

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Win - Dial Pad: JAWS: Add speed dial dialog role and label is not announced
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775)
=> fix(voiceover): Add speed dial dialog role and label is not announced

packages/node_modules/@webex/widget-number-pad/src/NumberPad.tsx
Win - Dial Pad: JAWS: Dial pad does not announce grouping relationship
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526781](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526781?src=confmacro)
=> (SPARK-526781)fix(voiceover): Win - Dial Pad: JAWS: Dial pad does not announce grouping relationship

package-lock.json, package.json, packages/node_modules/@webex/webex-sign-in-page/package.json, packages/node_modules/@webex/widget-call-history/package.json, packages/node_modules/@webex/widget-number-pad/package.json, packages/node_modules/@webex/widget-speed-dial/package.json, packages/node_modules/@webex/widget-voice-mail/package.json
Reverts webex/react-widgets#1389
=> Revert "fix(momemtumversion): upgrading momentumversion"

packages/node_modules/@webex/widget-call-history/src/CallHistoryItem.tsx, packages/node_modules/@webex/widget-call-history/src/utils/voiceOver.ts, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526782
Callhistory figma : https://www.figma.com/design/ey5FGtGp49mEQXnGwA7ZlO/%23319121-MSTeams-Call-Landing-Page-Redesign?node-id=3601-182902&t=1xHNQ2XkenlbvMzA-0
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526788
Voicemial figma: https://www.figma.com/design/ey5FGtGp49mEQXnGwA7ZlO/%23319121-MSTeams-Call-Landing-Page-Redesign?node-id=3601-182903&t=skTDfusXk3Dl8Y0M-0
=> fix(voiceover): callhistory and voicemail SR announce changes

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Win - Speed Dial: Keyboard Nav: Info toggletip button is not keyboard focusable
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526776](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526776)
=> Win - Speed Dial: Keyboard Nav: Info toggletip button is not keyboard focusable

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialItem.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDials.tsx
This PR consists of changes required to show call icon and create a hover like effect on speed dial items when using keyboard to focus.
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526774](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526774)
=> fix(speeddial): hover effect on keyboard focus

packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx, packages/node_modules/@webex/widget-voice-mail/src/utils/dateUtils.ts
Description: This PR contains voiceover announcements for the voicemail date and play and pause announcement.
Vidcast link: https://app.vidcast.io/share/13dae539-54ac-4db2-aa06-8b5426268c03
=> fix(voicemail): vm date announcement

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Win - Dial Pad: JAWS: Add speed dial dialog role and label is not announced
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775)
=> (SPARK-526775): Win - Dial Pad: JAWS: Add speed dial dialog role and label is not announced

packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx
Jira Link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526788
Added the instructions for how to focus play buttons for list item
=> fix(SPARK-526788): voiceover text for the play button

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.types.tsx, packages/node_modules/@webex/widget-speed-dial/src/SpeedDialModal.tsx
Win - Dial Pad: JAWS: Add speed dial dialog role and label is not announced
[https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526775)
=> (SPARK-526775): fix(voiceover): Win - Dial Pad: JAWS: Add speed dial dialog role and label is not announced

packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.styles.scss, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx
Description:
1. Win - Recent Calls: JAWS: Unread voicemails represents with icon is not conveyed to SR users
2. The play button does not focus if the voicemail has already been played.
Jira:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-543157
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526779
https://github.com/user-attachments/assets/80401df2-779d-4e37-9018-2ee19b4b72c4
=> fix(SPARK-543157): unread and voicemailplaybutton

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx
This pr consists of changes for the following issues
1. When adding directory contacts the first filed of the form is not auto focussed [https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-543223](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-543223)
2. Not able to save changes when editing a speed dial reliably. (e.g., Unable to save changes until a last name was added. Save button did not activate even if other entries, like number, were edited) [https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-523409](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-523409)
=> fix(speeddial): speed dial edit, directory contact focus

packages/node_modules/@webex/widget-speed-dial/src/SpeedDialForm.tsx
Implemented that Add a speed dial modal as a modal dialog and associate the visible title so the screen reader user understands the displayed content and its structure
=> SPARK-526796: Add a speed dial dialog does not announce dialog role or label

package-lock.json, package.json, packages/node_modules/@webex/webex-sign-in-page/package.json, packages/node_modules/@webex/widget-call-history/package.json, packages/node_modules/@webex/widget-number-pad/package.json, packages/node_modules/@webex/widget-speed-dial/package.json, packages/node_modules/@webex/widget-voice-mail/package.json
Reverts webex/react-widgets#1417
=> Revert "momentum-version-upgrade"

packages/node_modules/@webex/widget-number-pad/src/SearchContacts/CallSelectPopover.tsx, packages/node_modules/@webex/widget-number-pad/src/SearchContacts/SearchContactsItem.tsx
Description: In the ‘Dialpad’ tab, no instructions for keyboard users are provided on how to navigate the embedded action buttons for the search suggestions.
Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526788
https://jira-eng-gpk2.cisco.com/jira/secure/attachment/1273443/SPARK-526788-2-not%20fixed.png
di
https://github.com/user-attachments/assets/f98f6a5f-2e0b-4293-8f5b-d1a77d2caeb9
=> fix(SPARK-548628): Dialpad nstructions for keyboard users

packages/node_modules/@webex/react-component-activity-share-file/src/styles.css, packages/node_modules/@webex/react-component-activity-text/src/__snapshots__/index.test.js.snap, packages/node_modules/@webex/react-component-activity-text/src/index.js, packages/node_modules/@webex/react-component-activity-text/src/styles.css, packages/node_modules/@webex/react-container-activity-list/src/__snapshots__/index.test.js.snap
Text color change - https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539202
Chat history accessibility - https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539187
- Changed color from a light grey to a suggested darker shade
- Changed the text div -> anchor tag to make it accessible along with css changes
https://github.com/user-attachments/assets/8df24608-04f3-45a3-b452-d01c33707123
Before.  ![Screenshot 2024-07-31 at 12 41 20 PM](https://github.com/user-attachments/assets/8ffb1de0-fa5c-4d7e-bfe6-9675eabba7c7).
After  ![Screenshot 2024-07-31 at 12 41 38 PM](https://github.com/user-attachments/assets/52696a00-7171-4b82-96d4-1fee06316abc)
=> fix(space-widget): improve-accessibility

packages/node_modules/@webex/widget-voice-mail/src/ScrubbingBar.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailItem.tsx, packages/node_modules/@webex/widget-voice-mail/src/VoicemailPlaybackControls.tsx
Description: Voicemail UI seek bar issue.
Jira Link:
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-523426
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526742
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-526773
https://github.com/user-attachments/assets/a13226ab-ac83-4af9-9681-ed3438788ea5
=> fix(spark-526773): Voicemail seekbar implementation

.github/workflows/pull-request.yml
Completes Adhoc
This PR adds github action's checks in react-widgets. GIthub actions is a necessary now because circleCI builds are getting longer and they are failling because we dont have enough resources.
Working github actions run - https://github.com/Shreyas281299/react-widgets/actions/runs/11453800566
These github actions checks are specifically written for yarn workspaces.
=> tooling(github-actions): add-pull-request-yml

.github/PULL_REQUEST_TEMPLATE.md
Pull request template with GAI
=> chore(pulls): update pull request template

packages/node_modules/@webex/widget-demo/src/components/demo-widget/styles.css
Adjusted positioning and styling of .stickyButton, widgetSpaceComponentContainer, and  widgetRecentsComponentContainer to ensure widgets do not overlap and remain fully visible
- Added media queries for devices under 480px width to improve usability and accessibility.
- Ensured hidden states (.hidden) are handled correctly when space or recents widget is not available.
- Updated CSS for .stickyButton to properly center and position on smaller screens.
- Modified .widgetSpaceComponentContainer and .widgetRecentsComponentContainer with responsive styles (width: 100%, max-width: 100%, and position: relative) under @media (max-width: 480px)
- Added .hidden class handling to hide tabs when the respective widget (recents or space) is not present. …
=> fix(space-widget): space widget responsive design
